<?php
/**
 * Asset CleanUp Lite — Getting Started page module.
 *
 * Expected optional variable from the controller:
 *
 * $wpacu_gs_config = array(
 *     'version'             => WPACU_LITE_PLUGIN_VERSION,
 *     'test_mode_enabled'   => false,
 *     'progress_storage_key'=> 'wpacu_getting_started_progress_v1_blog_1',
 *     'urls'                => array(...),
 * );
 *
 * PHP 5.6 compatible.
 */

if ( ! isset($data) ) {
    exit;
}

$wpacu_for = isset($_GET['wpacu_for'])
    ? sanitize_key(wp_unslash($_GET['wpacu_for']))
    : '';

$wpacu_getting_started_url = add_query_arg(
    'page',
    'wpassetcleanup_getting_started',
    admin_url('admin.php')
);

$wpacu_lite_vs_pro_url = add_query_arg(
    array(
        'page'      => WPACU_PLUGIN_ID . '_getting_started',
        'wpacu_for' => 'lite-vs-pro',
    ),
    admin_url('admin.php')
);

if ('lite-vs-pro' === $wpacu_for) {
    $wpacu_lvp_config = array(
        'version' => WPACU_PLUGIN_VERSION,
        'urls'    => array(
            'getting_started' => $wpacu_getting_started_url,
            'manager'         => admin_url('admin.php?page=' . WPACU_PLUGIN_ID . '_assets_manager'),
            'help'            => admin_url('admin.php?page=' . WPACU_PLUGIN_ID . '_get_help'),
            'pro'             => 'https://www.gabelivan.com/items/wp-asset-cleanup-pro/',
            'pricing'         => 'https://www.gabelivan.com/items/wp-asset-cleanup-pro/',
            'pro_docs'        => 'https://www.assetcleanup.com/docs/',
        ),
    );

    include WPACU_LITE_DIR . '/templates/_admin-page-getting-started-areas/_lite-vs-pro.php';
    return;
}

$wpacu_gs_config = (isset($wpacu_gs_config) && is_array($wpacu_gs_config))
    ? $wpacu_gs_config
    : array();

$wpacu_gs_blog_id   = function_exists('get_current_blog_id') ? (int) get_current_blog_id() : 1;
$wpacu_gs_admin_url = function_exists('admin_url') ? admin_url('admin.php') : 'admin.php';
$wpacu_gs_version   = defined('WPACU_PLUGIN_VERSION') ? WPACU_PLUGIN_VERSION : '';
$wpacu_gs_logo_mark = defined('WPACU_PLUGIN_URL')
    ? trailingslashit(WPACU_PLUGIN_URL) . 'assets/images/wpacu-logo-mark-white.png'
    : '';

$testModeEnabled    = isset($data['settings']['test_mode']) && (int)$data['settings']['test_mode'] === 1;

$wpacu_gs_defaults = array(
    'version'              => $wpacu_gs_version,
    'test_mode_enabled'    => $testModeEnabled,
    'progress_storage_key' => 'wpacu_getting_started_progress_v1_blog_' . $wpacu_gs_blog_id,

    'urls'                 => array(
        // Replace these defaults with the exact URLs already generated by the plugin controller.
        'logo_mark'       => $wpacu_gs_logo_mark,
        'test_mode'       => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_settings&wpacu_selected_tab_area=wpacu-setting-test-mode',
        'manager'         => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_assets_manager',
        'settings'        => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_settings',
        'overview'        => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_overview',
        'lite_vs_pro'     => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_getting_started&wpacu_for=lite-vs-pro',
        'help'            => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_get_help',
        'plugins_manager' => $wpacu_gs_admin_url . '?page=' . WPACU_PLUGIN_ID . '_plugins_manager',

        'docs'            => 'https://www.assetcleanup.com/docs/',
        'pagespeed'       => 'https://pagespeed.web.dev/',
        'pro'             => 'https://www.gabelivan.com/items/wp-asset-cleanup-pro/',
    ),
);

$wpacu_gs_config = array_replace_recursive($wpacu_gs_defaults, $wpacu_gs_config);
$wpacu_gs_urls   = $wpacu_gs_config['urls'];

$wpacu_gs_test_mode_enabled = ! empty($wpacu_gs_config['test_mode_enabled']);
$wpacu_gs_test_mode_class   = $wpacu_gs_test_mode_enabled ? ' wpacu-is-on ' : '';
$wpacu_gs_test_mode_text    = $wpacu_gs_test_mode_enabled
    ? esc_html__('Test Mode is ON', 'wp-asset-clean-up')
    : esc_html__('Test Mode is OFF', 'wp-asset-clean-up');
?>

<div
    id="wpacu-getting-started-page-wrap"
    data-progress-storage-key="<?php echo esc_attr($wpacu_gs_config['progress_storage_key']); ?>"
>
    <section class="wpacu-gs-hero" aria-labelledby="wpacu-gs-page-title">
        <div class="wpacu-gs-hero-copy">
            <div class="wpacu-gs-hero-meta">
                <div class="wpacu-gs-hero-identity">
                    <?php if ( ! empty($wpacu_gs_urls['logo_mark']) ) : ?>
                        <span class="wpacu-gs-hero-mark-shell" aria-hidden="true">
                            <img
                                class="wpacu-gs-hero-mark"
                                src="<?php echo esc_url($wpacu_gs_urls['logo_mark']); ?>"
                                alt=""
                            >
                        </span>
                    <?php endif; ?>

                    <div class="wpacu-gs-hero-eyebrow">
                        <?php esc_html_e('Getting Started · A controlled first win', 'wp-asset-clean-up'); ?>
                    </div>
                </div>

                <div class="wpacu-gs-test-mode-status<?php echo esc_attr($wpacu_gs_test_mode_class); ?>">
                    <?php echo $wpacu_gs_test_mode_text; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
                </div>
            </div>

            <h1 id="wpacu-gs-page-title">
                <?php esc_html_e('Make WordPress load only what each page needs.', 'wp-asset-clean-up'); ?>
            </h1>

            <p class="wpacu-gs-hero-description">
                <?php
                echo wp_kses_post(
                    __('Asset CleanUp shows the CSS and JavaScript requested on a page and lets you stop files from loading where their feature is absent. Start with <strong>one obvious rule</strong>, verify it privately, and expand only when the result is clear.', 'wp-asset-clean-up')
                );
                ?>
            </p>

            <div class="wpacu-gs-hero-actions">
                <a class="wpacu-gs-button wpacu-gs-button--primary" href="#wpacu-gs-first-win">
                    <?php esc_html_e('Start the guided walkthrough', 'wp-asset-clean-up'); ?>
                </a>

                <a class="wpacu-gs-button wpacu-gs-button--ghost-light" href="<?php echo esc_url($wpacu_gs_urls['manager']); ?>">
                    <?php esc_html_e('Open CSS & JS Manager', 'wp-asset-clean-up'); ?>
                </a>
            </div>

            <ul class="wpacu-gs-hero-trust">
                <li><?php esc_html_e('Original theme and plugin files stay untouched', 'wp-asset-clean-up'); ?></li>
                <li><?php esc_html_e('Test Mode keeps visitors on the normal site', 'wp-asset-clean-up'); ?></li>
                <li><?php esc_html_e('Works alongside page caching and a CDN', 'wp-asset-clean-up'); ?></li>
            </ul>
        </div>

        <div class="wpacu-gs-hero-visual" aria-label="<?php esc_attr_e('Example of loading only the assets required by a page', 'wp-asset-clean-up'); ?>">
            <div class="wpacu-gs-browser">
                <div class="wpacu-gs-browser-bar" aria-hidden="true">
                    <span class="wpacu-gs-browser-dot"></span>
                    <span class="wpacu-gs-browser-dot"></span>
                    <span class="wpacu-gs-browser-dot"></span>
                    <span class="wpacu-gs-browser-address"></span>
                </div>

                <div class="wpacu-gs-browser-content">
                    <p class="wpacu-gs-browser-page-title"><?php esc_html_e('Example: About page', 'wp-asset-clean-up'); ?></p>
                    <p class="wpacu-gs-browser-page-subtitle"><?php esc_html_e('Conditional loading, not blind deletion', 'wp-asset-clean-up'); ?></p>

                    <div class="wpacu-gs-resource-group">
                        <div class="wpacu-gs-resource-label">
                            <span><?php esc_html_e('Needed here', 'wp-asset-clean-up'); ?></span>
                            <strong><?php esc_html_e('Loaded', 'wp-asset-clean-up'); ?></strong>
                        </div>

                        <div class="wpacu-gs-resource-list">
                            <span class="wpacu-gs-resource-chip">theme.css</span>
                            <span class="wpacu-gs-resource-chip">navigation.js</span>
                            <span class="wpacu-gs-resource-chip">global.js</span>
                        </div>
                    </div>

                    <div class="wpacu-gs-resource-group">
                        <div class="wpacu-gs-resource-label">
                            <span><?php esc_html_e('Not used on this page', 'wp-asset-clean-up'); ?></span>
                            <strong><?php esc_html_e('Skipped', 'wp-asset-clean-up'); ?></strong>
                        </div>

                        <div class="wpacu-gs-resource-list">
                            <span class="wpacu-gs-resource-chip is-skipped">contact-form.css</span>
                            <span class="wpacu-gs-resource-chip is-skipped">slider.js</span>
                        </div>
                    </div>

                    <div class="wpacu-gs-browser-result">
                        <span><?php esc_html_e('2 page-irrelevant assets skipped', 'wp-asset-clean-up'); ?></span>
                        <span><?php esc_html_e('No files deleted', 'wp-asset-clean-up'); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="wpacu-gs-page-nav-wrap">
        <nav class="wpacu-gs-page-nav" data-wpacu-gs-page-nav aria-label="<?php esc_attr_e('Getting Started sections', 'wp-asset-clean-up'); ?>">
            <span class="wpacu-gs-page-nav-label"><?php esc_html_e('On this page', 'wp-asset-clean-up'); ?></span>
            <a href="#wpacu-gs-concept"><?php esc_html_e('The idea', 'wp-asset-clean-up'); ?></a>
            <a href="#wpacu-gs-first-win"><?php esc_html_e('First safe win', 'wp-asset-clean-up'); ?></a>
            <a href="#wpacu-gs-vitals"><?php esc_html_e('Core Web Vitals', 'wp-asset-clean-up'); ?></a>
            <a href="#wpacu-gs-product-map"><?php esc_html_e('Where to work', 'wp-asset-clean-up'); ?></a>
            <a href="#wpacu-gs-lite-vs-pro"><?php esc_html_e('Lite or Pro', 'wp-asset-clean-up'); ?></a>
        </nav>
    </div>

    <div class="wpacu-gs-orientation" aria-label="<?php esc_attr_e('Optimization workflow at a glance', 'wp-asset-clean-up'); ?>">
        <article class="wpacu-gs-orientation-item">
            <span class="wpacu-gs-icon wpacu-gs-icon--eye" aria-hidden="true"></span>
            <div>
                <span class="wpacu-gs-orientation-number"><?php esc_html_e('Step 1', 'wp-asset-clean-up'); ?></span>
                <h3><?php esc_html_e('See what the page loads', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Identify files by handle, source, and the plugin or theme that registered them.', 'wp-asset-clean-up'); ?></p>
            </div>
        </article>

        <article class="wpacu-gs-orientation-item">
            <span class="wpacu-gs-icon wpacu-gs-icon--route" aria-hidden="true"></span>
            <div>
                <span class="wpacu-gs-orientation-number"><?php esc_html_e('Step 2', 'wp-asset-clean-up'); ?></span>
                <h3><?php esc_html_e('Decide where each file belongs', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Unload only when the related feature is absent from the current page.', 'wp-asset-clean-up'); ?></p>
            </div>
        </article>

        <article class="wpacu-gs-orientation-item">
            <span class="wpacu-gs-icon wpacu-gs-icon--shield" aria-hidden="true"></span>
            <div>
                <span class="wpacu-gs-orientation-number"><?php esc_html_e('Step 3', 'wp-asset-clean-up'); ?></span>
                <h3><?php esc_html_e('Verify before visitors see it', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Use Test Mode, make one change at a time, and test the actual functionality.', 'wp-asset-clean-up'); ?></p>
            </div>
        </article>
    </div>

    <section id="wpacu-gs-concept" class="wpacu-gs-section" aria-labelledby="wpacu-gs-concept-title">
        <div class="wpacu-gs-section-heading">
            <div class="wpacu-gs-kicker"><?php esc_html_e('The mental model', 'wp-asset-clean-up'); ?></div>
            <h2 id="wpacu-gs-concept-title" class="wpacu-gs-section-title">
                <?php esc_html_e('A file can be useful on one page and unnecessary on another.', 'wp-asset-clean-up'); ?>
            </h2>
            <p class="wpacu-gs-section-intro">
                <?php esc_html_e('Unloading is not deleting, and “unnecessary here” does not mean “bad code.” You are making a routing decision: this resource belongs on these pages, but not on those pages.', 'wp-asset-clean-up'); ?>
            </p>
        </div>

        <div class="wpacu-gs-mental-model">
            <article class="wpacu-gs-card wpacu-gs-concept-copy">
                <h3><?php esc_html_e('Think in page contexts, not in plugin names alone', 'wp-asset-clean-up'); ?></h3>

                <p>
                    <?php esc_html_e('A contact form plugin may be essential to the Contact page and irrelevant to the About page. A slider script may be needed on the homepage and unnecessary everywhere else.', 'wp-asset-clean-up'); ?>
                </p>

                <p>
                    <?php esc_html_e('The safest rules begin with a feature you can point to on the screen. When the feature is absent, its dedicated asset is often a reasonable candidate to test.', 'wp-asset-clean-up'); ?>
                </p>

                <div class="wpacu-gs-definition">
                    <?php
                    echo wp_kses_post(
                        __('<strong>Asset</strong> = a CSS or JavaScript resource. <strong>Rule</strong> = an instruction that changes how it loads. <strong>Context</strong> = the page, template, or request where that rule applies.', 'wp-asset-clean-up')
                    );
                    ?>
                </div>
            </article>

            <article class="wpacu-gs-card wpacu-gs-context-matrix">
                <div class="wpacu-gs-context-matrix-header">
                    <h3><?php esc_html_e('The same three assets across three page types', 'wp-asset-clean-up'); ?></h3>
                    <span><?php esc_html_e('Illustrative example', 'wp-asset-clean-up'); ?></span>
                </div>

                <div class="wpacu-gs-matrix-grid" role="table" aria-label="<?php esc_attr_e('Example asset loading by page context', 'wp-asset-clean-up'); ?>">
                    <div class="wpacu-gs-matrix-cell is-heading" role="columnheader"><?php esc_html_e('Asset', 'wp-asset-clean-up'); ?></div>
                    <div class="wpacu-gs-matrix-cell is-heading" role="columnheader"><?php esc_html_e('Home', 'wp-asset-clean-up'); ?></div>
                    <div class="wpacu-gs-matrix-cell is-heading" role="columnheader"><?php esc_html_e('Contact', 'wp-asset-clean-up'); ?></div>
                    <div class="wpacu-gs-matrix-cell is-heading" role="columnheader"><?php esc_html_e('Product', 'wp-asset-clean-up'); ?></div>

                    <div class="wpacu-gs-matrix-cell is-asset" role="rowheader">slider.js</div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-needed"><?php esc_html_e('Load', 'wp-asset-clean-up'); ?></span></div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-skipped"><?php esc_html_e('Skip', 'wp-asset-clean-up'); ?></span></div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-skipped"><?php esc_html_e('Skip', 'wp-asset-clean-up'); ?></span></div>

                    <div class="wpacu-gs-matrix-cell is-asset" role="rowheader">contact-form.css</div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-skipped"><?php esc_html_e('Skip', 'wp-asset-clean-up'); ?></span></div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-needed"><?php esc_html_e('Load', 'wp-asset-clean-up'); ?></span></div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-skipped"><?php esc_html_e('Skip', 'wp-asset-clean-up'); ?></span></div>

                    <div class="wpacu-gs-matrix-cell is-asset" role="rowheader">product-gallery.js</div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-skipped"><?php esc_html_e('Skip', 'wp-asset-clean-up'); ?></span></div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-skipped"><?php esc_html_e('Skip', 'wp-asset-clean-up'); ?></span></div>
                    <div class="wpacu-gs-matrix-cell"><span class="wpacu-gs-matrix-state is-needed"><?php esc_html_e('Load', 'wp-asset-clean-up'); ?></span></div>
                </div>
            </article>
        </div>
    </section>

    <section id="wpacu-gs-first-win" class="wpacu-gs-section" aria-labelledby="wpacu-gs-first-win-title">
        <div class="wpacu-gs-section-heading">
            <div class="wpacu-gs-kicker"><?php esc_html_e('Your first controlled optimization', 'wp-asset-clean-up'); ?></div>
            <h2 id="wpacu-gs-first-win-title" class="wpacu-gs-section-title">
                <?php esc_html_e('Ten minutes. One page. One clear rule.', 'wp-asset-clean-up'); ?>
            </h2>
            <p class="wpacu-gs-section-intro">
                <?php esc_html_e('Do not begin with a site-wide cleanup. Build confidence with a small change whose purpose and result you can explain.', 'wp-asset-clean-up'); ?>
            </p>
        </div>

        <div class="wpacu-gs-first-win-grid">
            <article class="wpacu-gs-card wpacu-gs-walkthrough">
                <div class="wpacu-gs-progress-head">
                    <div>
                        <h3><?php esc_html_e('Guided first-run checklist', 'wp-asset-clean-up'); ?></h3>
                        <p><?php esc_html_e('Ticking a step stores progress only in this browser.', 'wp-asset-clean-up'); ?></p>
                    </div>
                    <span class="wpacu-gs-progress-value" data-wpacu-gs-progress-text>0 of 5 complete</span>
                </div>

                <div
                    class="wpacu-gs-progress-track"
                    data-wpacu-gs-progress-track
                    role="progressbar"
                    aria-label="<?php esc_attr_e('Getting Started checklist progress', 'wp-asset-clean-up'); ?>"
                    aria-valuemin="0"
                    aria-valuemax="100"
                    aria-valuenow="0"
                >
                    <div class="wpacu-gs-progress-bar" data-wpacu-gs-progress-bar></div>
                </div>

                <ol class="wpacu-gs-checklist">
                    <li class="wpacu-gs-checkpoint">
                        <input id="wpacu-gs-check-1" type="checkbox" data-wpacu-gs-checkpoint="test-mode">
                        <div class="wpacu-gs-checkpoint-card">
                            <label for="wpacu-gs-check-1">
                                <span class="wpacu-gs-checkpoint-number">1</span>
                                <span>
                                    <span class="wpacu-gs-checkpoint-title"><?php esc_html_e('Enable Test Mode', 'wp-asset-clean-up'); ?></span>
                                    <span class="wpacu-gs-checkpoint-description"><?php esc_html_e('Your rules affect only your logged-in administrator session while visitors keep seeing the normal site.', 'wp-asset-clean-up'); ?></span>
                                </span>
                            </label>
                            <a class="wpacu-gs-checkpoint-action" href="<?php echo esc_url($wpacu_gs_urls['test_mode']); ?>"><?php esc_html_e('Open setting', 'wp-asset-clean-up'); ?></a>
                        </div>
                    </li>

                    <li class="wpacu-gs-checkpoint">
                        <input id="wpacu-gs-check-2" type="checkbox" data-wpacu-gs-checkpoint="simple-page">
                        <div class="wpacu-gs-checkpoint-card">
                            <label for="wpacu-gs-check-2">
                                <span class="wpacu-gs-checkpoint-number">2</span>
                                <span>
                                    <span class="wpacu-gs-checkpoint-title"><?php esc_html_e('Choose one simple page you understand', 'wp-asset-clean-up'); ?></span>
                                    <span class="wpacu-gs-checkpoint-description"><?php esc_html_e('Start with a normal content page—not checkout, login, account, booking, or another business-critical flow.', 'wp-asset-clean-up'); ?></span>
                                </span>
                            </label>
                            <a class="wpacu-gs-checkpoint-action" href="<?php echo esc_url($wpacu_gs_urls['manager']); ?>"><?php esc_html_e('Open manager', 'wp-asset-clean-up'); ?></a>
                        </div>
                    </li>

                    <li class="wpacu-gs-checkpoint">
                        <input id="wpacu-gs-check-3" type="checkbox" data-wpacu-gs-checkpoint="candidate">
                        <div class="wpacu-gs-checkpoint-card">
                            <label for="wpacu-gs-check-3">
                                <span class="wpacu-gs-checkpoint-number">3</span>
                                <span>
                                    <span class="wpacu-gs-checkpoint-title"><?php esc_html_e('Find one obvious candidate', 'wp-asset-clean-up'); ?></span>
                                    <span class="wpacu-gs-checkpoint-description"><?php esc_html_e('Example: a contact-form asset on a page with no form, or a slider asset on a text-only page.', 'wp-asset-clean-up'); ?></span>
                                </span>
                            </label>
                            <a class="wpacu-gs-checkpoint-action" href="#wpacu-gs-candidates"><?php esc_html_e('See good first candidates', 'wp-asset-clean-up'); ?></a>
                        </div>
                    </li>

                    <li class="wpacu-gs-checkpoint">
                        <input id="wpacu-gs-check-4" type="checkbox" data-wpacu-gs-checkpoint="single-rule">
                        <div class="wpacu-gs-checkpoint-card">
                            <label for="wpacu-gs-check-4">
                                <span class="wpacu-gs-checkpoint-number">4</span>
                                <span>
                                    <span class="wpacu-gs-checkpoint-title"><?php esc_html_e('Unload it only on that page and save', 'wp-asset-clean-up'); ?></span>
                                    <span class="wpacu-gs-checkpoint-description"><?php esc_html_e('Do not stack several changes together. A single rule makes the result easy to understand and reverse.', 'wp-asset-clean-up'); ?></span>
                                </span>
                            </label>
                            <a class="wpacu-gs-checkpoint-action" href="<?php echo esc_url($wpacu_gs_urls['manager']); ?>"><?php esc_html_e('Manage assets', 'wp-asset-clean-up'); ?></a>
                        </div>
                    </li>

                    <li class="wpacu-gs-checkpoint">
                        <input id="wpacu-gs-check-5" type="checkbox" data-wpacu-gs-checkpoint="verify">
                        <div class="wpacu-gs-checkpoint-card">
                            <label for="wpacu-gs-check-5">
                                <span class="wpacu-gs-checkpoint-number">5</span>
                                <span>
                                    <span class="wpacu-gs-checkpoint-title"><?php esc_html_e('Test, clear caches, then publish', 'wp-asset-clean-up'); ?></span>
                                    <span class="wpacu-gs-checkpoint-description"><?php esc_html_e('Check desktop and mobile, clear page/CDN cache, disable Test Mode when ready, and perform a final logged-out check.', 'wp-asset-clean-up'); ?></span>
                                </span>
                            </label>
                            <a class="wpacu-gs-checkpoint-action" href="<?php echo esc_url($wpacu_gs_urls['help']); ?>"><?php esc_html_e('Open Help', 'wp-asset-clean-up'); ?></a>
                        </div>
                    </li>
                </ol>

                <button class="wpacu-gs-progress-reset" type="button" data-wpacu-gs-progress-reset>
                    <?php esc_html_e('Reset this local checklist', 'wp-asset-clean-up'); ?>
                </button>
            </article>

            <aside id="wpacu-gs-candidates" class="wpacu-gs-card wpacu-gs-candidate-guide">
                <div class="wpacu-gs-candidate-block">
                    <h3><?php esc_html_e('Good first candidates', 'wp-asset-clean-up'); ?></h3>
                    <ul class="wpacu-gs-candidate-list">
                        <li><?php esc_html_e('Contact-form assets on pages without a form', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Slider or gallery assets on plain content pages', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Store-related assets on pages outside the shop flow', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Assets for a widget or block that is visibly absent', 'wp-asset-clean-up'); ?></li>
                    </ul>
                </div>

                <div class="wpacu-gs-candidate-block is-caution">
                    <h3><?php esc_html_e('Leave these for later', 'wp-asset-clean-up'); ?></h3>
                    <ul class="wpacu-gs-candidate-list">
                        <li><?php esc_html_e('The theme’s main stylesheet or global layout scripts', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('WordPress core dependencies such as jQuery when their role is unclear', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Cookie consent, security, analytics, checkout, account, or booking flows', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Files with unfamiliar names and many dependent assets', 'wp-asset-clean-up'); ?></li>
                    </ul>
                </div>

                <div class="wpacu-gs-cache-note">
                    <strong><?php esc_html_e('Caching can hide a correct change.', 'wp-asset-clean-up'); ?></strong>
                    <?php esc_html_e('Clear the relevant page cache, server cache, CDN cache, and generated CSS/JS cache before deciding that a rule did not work.', 'wp-asset-clean-up'); ?>
                </div>
            </aside>
        </div>
    </section>

    <section id="wpacu-gs-vitals" class="wpacu-gs-section" aria-labelledby="wpacu-gs-vitals-title">
        <div class="wpacu-gs-section-heading">
            <div class="wpacu-gs-kicker"><?php esc_html_e('Performance literacy', 'wp-asset-clean-up'); ?></div>
            <h2 id="wpacu-gs-vitals-title" class="wpacu-gs-section-title">
                <?php esc_html_e('Use PageSpeed Insights as a diagnostic—not a blind checklist.', 'wp-asset-clean-up'); ?>
            </h2>
            <p class="wpacu-gs-section-intro">
                <?php esc_html_e('A lower request count can help, but it is not the goal by itself. Pay attention to what blocks rendering, what keeps the main thread busy, and what real visitors experience.', 'wp-asset-clean-up'); ?>
            </p>
        </div>

        <article class="wpacu-gs-card wpacu-gs-vitals-intro-card">
            <div>
                <h3><?php esc_html_e('A stable, responsive website matters more than an artificial perfect score', 'wp-asset-clean-up'); ?></h3>
                <p>
                    <?php esc_html_e('Asset CleanUp can reduce unnecessary front-end work and create a stronger foundation for Core Web Vitals. It cannot guarantee a score or compensate for every server, image, layout, or third-party bottleneck.', 'wp-asset-clean-up'); ?>
                </p>
            </div>

            <div class="wpacu-gs-score-badge" aria-hidden="true">
                <span>100<small><?php esc_html_e('not the goal', 'wp-asset-clean-up'); ?></small></span>
            </div>
        </article>

        <div class="wpacu-gs-vitals-grid">
            <article class="wpacu-gs-vital-card">
                <span class="wpacu-gs-vital-code">LCP</span>
                <h3><?php esc_html_e('Largest Contentful Paint', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Unloading page-irrelevant render-blocking CSS or JavaScript can help the browser reach the main content sooner. Important images, CSS, and fonts still need correct prioritization.', 'wp-asset-clean-up'); ?></p>
            </article>

            <article class="wpacu-gs-vital-card">
                <span class="wpacu-gs-vital-code">INP</span>
                <h3><?php esc_html_e('Interaction to Next Paint', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Unnecessary JavaScript can add parsing, execution, and main-thread work. Removing scripts that have no job on the current page can improve responsiveness.', 'wp-asset-clean-up'); ?></p>
            </article>

            <article class="wpacu-gs-vital-card">
                <span class="wpacu-gs-vital-code">CLS</span>
                <h3><?php esc_html_e('Cumulative Layout Shift', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Font and image loading controls can support visual stability, but missing dimensions, dynamic content, advertisements, embeds, and layout choices also need attention.', 'wp-asset-clean-up'); ?></p>
            </article>
        </div>

        <div class="wpacu-gs-boundary-grid">
            <article class="wpacu-gs-card wpacu-gs-boundary-card">
                <h3><?php esc_html_e('What this plugin can directly influence', 'wp-asset-clean-up'); ?></h3>
                <ul class="wpacu-gs-boundary-list">
                    <li><?php esc_html_e('Unnecessary CSS and JavaScript', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Selected render-blocking requests', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Avoidable JavaScript execution', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Fonts, preloads, and image loading attributes', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Optional WordPress front-end output', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('How remaining CSS/JS is optimized', 'wp-asset-clean-up'); ?></li>
                </ul>
            </article>

            <article class="wpacu-gs-card wpacu-gs-boundary-card is-outside">
                <h3><?php esc_html_e('Other layers still need separate work', 'wp-asset-clean-up'); ?></h3>
                <ul class="wpacu-gs-boundary-list">
                    <li><?php esc_html_e('Slow hosting or high TTFB', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Oversized or poorly compressed images', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Third-party services and advertisements', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Database and backend processing', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Missing media dimensions and unstable layout', 'wp-asset-clean-up'); ?></li>
                    <li><?php esc_html_e('Page caching and CDN configuration', 'wp-asset-clean-up'); ?></li>
                </ul>
            </article>
        </div>
    </section>

    <section id="wpacu-gs-product-map" class="wpacu-gs-section" aria-labelledby="wpacu-gs-product-map-title">
        <div class="wpacu-gs-section-heading">
            <div class="wpacu-gs-kicker"><?php esc_html_e('The product map', 'wp-asset-clean-up'); ?></div>
            <h2 id="wpacu-gs-product-map-title" class="wpacu-gs-section-title">
                <?php esc_html_e('Use the right area for the right job.', 'wp-asset-clean-up'); ?>
            </h2>
            <p class="wpacu-gs-section-intro">
                <?php esc_html_e('Getting Started teaches the workflow. The areas below are where you inspect, configure, audit, and troubleshoot the actual rules.', 'wp-asset-clean-up'); ?>
            </p>
        </div>

        <div class="wpacu-gs-product-map">
            <article class="wpacu-gs-product-card">
                <span class="wpacu-gs-icon wpacu-gs-icon--manager" aria-hidden="true"></span>
                <h3><?php esc_html_e('CSS & JS Manager', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Inspect what a page loads, create targeted unload rules, add load exceptions, and manage page-level front-end assets.', 'wp-asset-clean-up'); ?></p>
                <a href="<?php echo esc_url($wpacu_gs_urls['manager']); ?>"><?php esc_html_e('Manage page assets', 'wp-asset-clean-up'); ?></a>
            </article>

            <article class="wpacu-gs-product-card is-overview">
                <span class="wpacu-gs-icon wpacu-gs-icon--overview" aria-hidden="true"></span>
                <h3><?php esc_html_e('Overview', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Review saved unload rules in one place, see where each rule applies, edit supported entries, and remove obsolete or dormant rules.', 'wp-asset-clean-up'); ?></p>
                <a href="<?php echo esc_url($wpacu_gs_urls['overview']); ?>"><?php esc_html_e('Review saved rules', 'wp-asset-clean-up'); ?></a>
            </article>

            <article class="wpacu-gs-product-card">
                <span class="wpacu-gs-icon wpacu-gs-icon--settings" aria-hidden="true"></span>
                <h3><?php esc_html_e('Settings', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Configure Test Mode, resource loading, fonts and preloads, minify/combine behavior, source cleanup, and plugin preferences.', 'wp-asset-clean-up'); ?></p>
                <a href="<?php echo esc_url($wpacu_gs_urls['settings']); ?>"><?php esc_html_e('Review settings', 'wp-asset-clean-up'); ?></a>
            </article>

            <article class="wpacu-gs-product-card">
                <span class="wpacu-gs-icon wpacu-gs-icon--help" aria-hidden="true"></span>
                <h3><?php esc_html_e('Help Center', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Use plain-English basics, quick troubleshooting, documentation, product support, or optional hands-on optimization help.', 'wp-asset-clean-up'); ?></p>
                <a href="<?php echo esc_url($wpacu_gs_urls['help']); ?>"><?php esc_html_e('Choose a help route', 'wp-asset-clean-up'); ?></a>
            </article>

            <article class="wpacu-gs-product-card">
                <span class="wpacu-gs-pro-badge"><?php esc_html_e('Pro', 'wp-asset-clean-up'); ?></span>
                <span class="wpacu-gs-icon wpacu-gs-icon--plugin" aria-hidden="true"></span>
                <h3><?php esc_html_e('Plugins Manager', 'wp-asset-clean-up'); ?></h3>
                <p><?php esc_html_e('Go beyond individual assets and stop an entire plugin from loading in selected contexts when its PHP and front-end output are not required.', 'wp-asset-clean-up'); ?></p>
                <a href="<?php echo esc_url($wpacu_gs_urls['plugins_manager']); ?>"><?php esc_html_e('See the Pro capability', 'wp-asset-clean-up'); ?></a>
            </article>
        </div>
    </section>

    <section id="wpacu-gs-lite-vs-pro" class="wpacu-gs-section" aria-labelledby="wpacu-gs-lite-vs-pro-title">
        <div class="wpacu-gs-section-heading">
            <div class="wpacu-gs-kicker"><?php esc_html_e('Choose based on complexity', 'wp-asset-clean-up'); ?></div>
            <h2 id="wpacu-gs-lite-vs-pro-title" class="wpacu-gs-section-title">
                <?php esc_html_e('Lite is for targeted cleanup. Pro is for scale and deeper control.', 'wp-asset-clean-up'); ?>
            </h2>
            <p class="wpacu-gs-section-intro">
                <?php esc_html_e('You do not need Pro to learn the workflow or make useful improvements. Upgrade when repeated manual work or broader rule coverage becomes the real limitation.', 'wp-asset-clean-up'); ?>
            </p>
        </div>

        <div class="wpacu-gs-editions">
            <div class="wpacu-gs-editions-grid">
                <article class="wpacu-gs-edition">
                    <span class="wpacu-gs-edition-label"><?php esc_html_e('Asset CleanUp Lite', 'wp-asset-clean-up'); ?></span>
                    <h3><?php esc_html_e('A strong place to learn and optimize key pages', 'wp-asset-clean-up'); ?></h3>
                    <p><?php esc_html_e('Stay with Lite when asset-level control covers the job and the number of pages or contexts remains manageable.', 'wp-asset-clean-up'); ?></p>

                    <ul class="wpacu-gs-edition-list">
                        <li><?php esc_html_e('Inspect and unload CSS/JavaScript at page level', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Work safely with Test Mode', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Use font, preload, Resource Loading, and cleanup controls', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Audit saved rules, edit supported entries, and remove obsolete ones from Overview', 'wp-asset-clean-up'); ?></li>
                    </ul>

                    <div class="wpacu-gs-edition-actions">
                        <a class="wpacu-gs-button" href="<?php echo esc_url($wpacu_gs_urls['manager']); ?>"><?php esc_html_e('Continue with Lite', 'wp-asset-clean-up'); ?></a>
                    </div>
                </article>

                <article class="wpacu-gs-edition is-pro">
                    <span class="wpacu-gs-edition-label"><?php esc_html_e('Asset CleanUp Pro', 'wp-asset-clean-up'); ?></span>
                    <h3><?php esc_html_e('More efficient when the website has many contexts', 'wp-asset-clean-up'); ?></h3>
                    <p><?php esc_html_e('Consider Pro when page-by-page work becomes repetitive or you need control that reaches beyond individual CSS and JavaScript files.', 'wp-asset-clean-up'); ?></p>

                    <ul class="wpacu-gs-edition-list">
                        <li><?php esc_html_e('Broader rules for post types, taxonomies, archives, search, and 404 pages', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Unload entire plugins in selected front-end contexts', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Conditional loading based on device or screen size', 'wp-asset-clean-up'); ?></li>
                        <li><?php esc_html_e('Advanced defer/async and more granular optimization controls', 'wp-asset-clean-up'); ?></li>
                    </ul>

                    <div class="wpacu-gs-edition-actions">
                        <a class="wpacu-gs-button wpacu-gs-button--primary" href="<?php echo esc_url($wpacu_gs_urls['lite_vs_pro']); ?>">
                            <?php esc_html_e('Compare Lite and Pro', 'wp-asset-clean-up'); ?>
                        </a>
                    </div>
                </article>
            </div>

            <div class="wpacu-gs-editions-note">
                <strong><?php esc_html_e('A good upgrade signal:', 'wp-asset-clean-up'); ?></strong>
                <?php esc_html_e('you understand the rules you want, but creating and maintaining them individually is taking too much time.', 'wp-asset-clean-up'); ?>
            </div>
        </div>
    </section>

    <section class="wpacu-gs-final-cta" aria-labelledby="wpacu-gs-final-title">
        <div class="wpacu-gs-final-cta-copy">
            <h2 id="wpacu-gs-final-title"><?php esc_html_e('Ready to make one controlled change?', 'wp-asset-clean-up'); ?></h2>
            <p><?php esc_html_e('Turn on Test Mode, choose a page you understand, and test one obvious candidate. The Help Center is there when something is unclear.', 'wp-asset-clean-up'); ?></p>
        </div>

        <div class="wpacu-gs-final-cta-actions">
            <?php if (! $wpacu_gs_test_mode_enabled) : ?>
                <a class="wpacu-gs-button wpacu-gs-button--primary" href="<?php echo esc_url($wpacu_gs_urls['test_mode']); ?>">
                    <?php esc_html_e('Turn on Test Mode', 'wp-asset-clean-up'); ?>
                </a>
            <?php else : ?>
                <a class="wpacu-gs-button wpacu-gs-button--primary" href="<?php echo esc_url($wpacu_gs_urls['manager']); ?>">
                    <?php esc_html_e('Open CSS & JS Manager', 'wp-asset-clean-up'); ?>
                </a>
            <?php endif; ?>

            <a class="wpacu-gs-button wpacu-gs-button--ghost-light" href="<?php echo esc_url($wpacu_gs_urls['help']); ?>">
                <?php esc_html_e('Open Help Center', 'wp-asset-clean-up'); ?>
            </a>
        </div>
    </section>

    <p class="wpacu-gs-footnote">
        <?php
        echo wp_kses_post(
            __('Asset CleanUp does not edit the original theme or plugin files and does not replace page caching. Performance results vary by website, page, configuration, device, and network.', 'wp-asset-clean-up')
        );
        ?>
    </p>
</div>

<script>
    /* global window, document */
    (function () {
        'use strict';

        var root = document.getElementById('wpacu-getting-started-page-wrap');

        if (!root) {
            return;
        }

        root.classList.add('has-js');

        var reducedMotion = false;

        if (window.matchMedia) {
            reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        }

        /*
         * Guided checklist
         *
         * This is deliberately local to the current browser. It is an onboarding aid,
         * not a claim that Asset CleanUp has detected the underlying task as complete.
         */
        var storageKey = root.getAttribute('data-progress-storage-key') || 'wpacu_getting_started_progress_v1';
        var checkpoints = root.querySelectorAll('[data-wpacu-gs-checkpoint]');
        var progressBar = root.querySelector('[data-wpacu-gs-progress-bar]');
        var progressText = root.querySelector('[data-wpacu-gs-progress-text]');
        var progressTrack = root.querySelector('[data-wpacu-gs-progress-track]');
        var resetButton = root.querySelector('[data-wpacu-gs-progress-reset]');

        function readStoredProgress() {
            try {
                var rawValue = window.localStorage.getItem(storageKey);
                var parsedValue = rawValue ? JSON.parse(rawValue) : [];

                return Array.isArray(parsedValue) ? parsedValue : [];
            } catch (error) {
                return [];
            }
        }

        function writeStoredProgress(completedIds) {
            try {
                window.localStorage.setItem(storageKey, JSON.stringify(completedIds));
            } catch (error) {
                // Storage can be unavailable in private or restricted browser contexts.
            }
        }

        function getCompletedCheckpointIds() {
            var completedIds = [];

            Array.prototype.forEach.call(checkpoints, function (checkpoint) {
                if (checkpoint.checked) {
                    completedIds.push(checkpoint.getAttribute('data-wpacu-gs-checkpoint'));
                }
            });

            return completedIds;
        }

        function updateProgressDisplay() {
            var total = checkpoints.length;
            var completed = getCompletedCheckpointIds().length;
            var percentage = total > 0 ? Math.round((completed / total) * 100) : 0;

            if (progressBar) {
                progressBar.style.width = percentage + '%';
            }

            if (progressText) {
                progressText.textContent = completed + ' of ' + total + ' complete';
            }

            if (progressTrack) {
                progressTrack.setAttribute('aria-valuenow', String(percentage));
                progressTrack.setAttribute('aria-valuetext', completed + ' of ' + total + ' steps complete');
            }
        }

        if (checkpoints.length) {
            var storedProgress = readStoredProgress();

            Array.prototype.forEach.call(checkpoints, function (checkpoint) {
                var checkpointId = checkpoint.getAttribute('data-wpacu-gs-checkpoint');

                checkpoint.checked = storedProgress.indexOf(checkpointId) !== -1;

                checkpoint.addEventListener('change', function () {
                    writeStoredProgress(getCompletedCheckpointIds());
                    updateProgressDisplay();
                });
            });

            updateProgressDisplay();
        }

        if (resetButton) {
            resetButton.addEventListener('click', function () {
                Array.prototype.forEach.call(checkpoints, function (checkpoint) {
                    checkpoint.checked = false;
                });

                writeStoredProgress([]);
                updateProgressDisplay();

                if (checkpoints.length) {
                    checkpoints[0].focus();
                }
            });
        }

        /* Keep nested action links from being interpreted as checklist clicks. */
        Array.prototype.forEach.call(root.querySelectorAll('.wpacu-gs-checkpoint-action'), function (actionLink) {
            actionLink.addEventListener('click', function (event) {
                event.stopPropagation();
            });
        });

        /*
         * In-page navigation
         */
        var navigation = root.querySelector('[data-wpacu-gs-page-nav]');
        var navigationLinks = navigation ? navigation.querySelectorAll('a[href^="#wpacu-gs-"]') : [];
        var sections = [];

        Array.prototype.forEach.call(navigationLinks, function (link) {
            var targetId = link.getAttribute('href').slice(1);
            var target = document.getElementById(targetId);

            if (target) {
                sections.push({
                    id: targetId,
                    element: target,
                    link: link
                });
            }

            link.addEventListener('click', function (event) {
                var destination = document.getElementById(targetId);

                if (!destination) {
                    return;
                }

                event.preventDefault();

                destination.scrollIntoView({
                    behavior: reducedMotion ? 'auto' : 'smooth',
                    block: 'start'
                });

                if (window.history && window.history.replaceState) {
                    window.history.replaceState(null, '', '#' + targetId);
                }
            });
        });

        function setActiveNavigationLink(activeId) {
            Array.prototype.forEach.call(navigationLinks, function (link) {
                var isActive = link.getAttribute('href') === '#' + activeId;

                link.classList.toggle('is-active', isActive);

                if (isActive) {
                    link.setAttribute('aria-current', 'location');
                } else {
                    link.removeAttribute('aria-current');
                }
            });
        }

        if ('IntersectionObserver' in window && sections.length) {
            var visibleSections = {};
            var observer = new window.IntersectionObserver(function (entries) {
                Array.prototype.forEach.call(entries, function (entry) {
                    visibleSections[entry.target.id] = entry.isIntersecting ? entry.intersectionRatio : 0;
                });

                var activeSection = null;
                var activeRatio = -1;

                sections.forEach(function (section) {
                    var ratio = visibleSections[section.id] || 0;

                    if (ratio > activeRatio) {
                        activeRatio = ratio;
                        activeSection = section;
                    }
                });

                if (activeSection && activeRatio > 0) {
                    setActiveNavigationLink(activeSection.id);
                }
            }, {
                root: null,
                rootMargin: '-18% 0px -62% 0px',
                threshold: [0, 0.1, 0.25, 0.5, 0.75]
            });

            sections.forEach(function (section) {
                observer.observe(section.element);
            });
        } else if (sections.length) {
            var ticking = false;

            window.addEventListener('scroll', function () {
                if (ticking) {
                    return;
                }

                ticking = true;

                window.requestAnimationFrame(function () {
                    var activeSection = sections[0];
                    var closestDistance = Number.POSITIVE_INFINITY;

                    sections.forEach(function (section) {
                        var distance = Math.abs(section.element.getBoundingClientRect().top - 120);

                        if (distance < closestDistance) {
                            closestDistance = distance;
                            activeSection = section;
                        }
                    });

                    setActiveNavigationLink(activeSection.id);
                    ticking = false;
                });
            }, { passive: true });
        }

        if (sections.length) {
            var initialHash = window.location.hash ? window.location.hash.slice(1) : '';
            var initialSectionExists = sections.some(function (section) {
                return section.id === initialHash;
            });

            setActiveNavigationLink(initialSectionExists ? initialHash : sections[0].id);
        }
    }());

    // Candidates
    (function () {
        'use strict';

        var pageWrap = document.getElementById('wpacu-getting-started-page-wrap');

        if (! pageWrap) {
            return;
        }

        var targetId = 'wpacu-gs-candidates';
        var target = document.getElementById(targetId);

        if (! target) {
            return;
        }

        /*
         * Highlight only the first block: "Good first candidates".
         * The caution block must remain unchanged.
         */
        var candidateBlock = target.querySelector(
            '.wpacu-gs-candidate-block:not(.is-caution)'
        );

        var links = pageWrap.querySelectorAll(
            'a[href="#' + targetId + '"], ' +
            'a[href$="#' + targetId + '"]'
        );

        if (! links.length) {
            return;
        }

        var highlightStartTimeout = null;
        var highlightEndTimeout = null;

        function removeHighlights() {
            target.classList.remove('wpacu-gs-is-highlighted');

            if (candidateBlock) {
                candidateBlock.classList.remove('wpacu-gs-is-highlighted');
            }
        }

        function highlightCandidates() {
            if (highlightEndTimeout) {
                window.clearTimeout(highlightEndTimeout);
            }

            removeHighlights();

            /* Force a reflow so both animations restart on repeated clicks. */
            void target.offsetWidth;

            target.classList.add('wpacu-gs-is-highlighted');

            if (candidateBlock) {
                candidateBlock.classList.add('wpacu-gs-is-highlighted');
            }

            highlightEndTimeout = window.setTimeout(function () {
                removeHighlights();
                highlightEndTimeout = null;
            }, 1700);
        }

        function scrollToTarget(event) {
            event.preventDefault();

            var reduceMotion = window.matchMedia &&
                window.matchMedia('(prefers-reduced-motion: reduce)').matches;

            if (highlightStartTimeout) {
                window.clearTimeout(highlightStartTimeout);
            }

            target.scrollIntoView({
                behavior: reduceMotion ? 'auto' : 'smooth',
                block: 'center'
            });

            /*
             * Start the two highlights after the smooth scroll has begun,
             * so the destination and the relevant inner block are obvious.
             */
            highlightStartTimeout = window.setTimeout(function () {
                highlightCandidates();
                highlightStartTimeout = null;
            }, reduceMotion ? 0 : 300);

            if (window.history && window.history.replaceState) {
                window.history.replaceState(
                    null,
                    '',
                    window.location.pathname +
                    window.location.search +
                    '#' + targetId
                );
            }
        }

        for (var i = 0; i < links.length; i++) {
            links[i].addEventListener('click', scrollToTarget);
        }
    }());
</script>
