<?php
/**
 * WP language locales.
 */
// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$country_list = array(
	'AD' => array(
		'en' => 'Andorra',
		'fr' => 'Andorre',
		'es' => 'Andorra',
		'it' => 'Andorra',
		'hi' => 'अंडोरा',
	),
	'AE' => array(
		'en' => 'United Arab Emirates',
		'fr' => 'Émirats arabes unis',
		'es' => 'Emiratos Árabes Unidos',
		'it' => 'Emirati Arabi Uniti',
		'hi' => 'संयुक्त अरब अमीरात',
	),
	'AF' => array(
		'en' => 'Afghanistan',
		'fr' => 'Afghanistan',
		'es' => 'Afganistán',
		'it' => 'Afghanistan',
		'hi' => 'अफ़गानिस्तान',
	),
	'AG' => array(
		'en' => 'Antigua and Barbuda',
		'fr' => 'Antigua-et-Barbuda',
		'es' => 'Antigua y Barbuda',
		'it' => 'Antigua e Barbuda',
		'hi' => 'एंटिगुआ और बारबुडा',
	),
	'AI' => array(
		'en' => 'Anguilla',
		'fr' => 'Anguilla',
		'es' => 'Anguila',
		'it' => 'Anguilla',
		'hi' => 'एंग्विला',
	),
	'AL' => array(
		'en' => 'Albania',
		'fr' => 'Albanie',
		'es' => 'Albania',
		'it' => 'Albania',
		'hi' => 'अल्बानिया',
	),
	'AM' => array(
		'en' => 'Armenia',
		'fr' => 'Arménie',
		'es' => 'Armenia',
		'it' => 'Armenia',
		'hi' => 'आर्मेनिया',
	),
	'AN' => array(
		'en' => 'Netherlands Antilles',
		'fr' => 'Antilles néerlandaises',
		'es' => 'Antillas Neerlandesas',
		'it' => 'Antille Olandesi',
		'hi' => 'नीदरलैंड्स एंटिल्स',
	),
	'AO' => array(
		'en' => 'Angola',
		'fr' => 'Angola',
		'es' => 'Angola',
		'it' => 'Angola',
		'hi' => 'अंगोला',
	),
	'AQ' => array(
		'en' => 'Antarctica',
		'fr' => 'Antarctique',
		'es' => 'Antártida',
		'it' => 'Antartide',
		'hi' => 'अंटार्कटिका',
	),
	'AR' => array(
		'en' => 'Argentina',
		'fr' => 'Argentine',
		'es' => 'Argentina',
		'it' => 'Argentina',
		'hi' => 'अर्जेंटीना',
	),
	'AS' => array(
		'en' => 'American Samoa',
		'fr' => 'Samoa américaines',
		'es' => 'Samoa Americana',
		'it' => 'Samoa Americane',
		'hi' => 'अमेरिकन समोआ',
	),
	'AT' => array(
		'en' => 'Austria',
		'fr' => 'Autriche',
		'es' => 'Austria',
		'it' => 'Austria',
		'hi' => 'ऑस्ट्रिया',
	),
	'AU' => array(
		'en' => 'Australia',
		'fr' => 'Australie',
		'es' => 'Australia',
		'it' => 'Australia',
		'hi' => 'ऑस्ट्रेलिया',
	),
	'AW' => array(
		'en' => 'Aruba',
		'fr' => 'Aruba',
		'es' => 'Aruba',
		'it' => 'Aruba',
		'hi' => 'अरूबा',
	),
	'AX' => array(
		'en' => 'Åland Islands',
		'fr' => 'Îles Åland',
		'es' => 'Islas Åland',
		'it' => 'Isole Åland',
		'hi' => 'ओलैंड द्वीपसमूह',
	),
	'AZ' => array(
		'en' => 'Azerbaijan',
		'fr' => 'Azerbaïdjan',
		'es' => 'Azerbaiyán',
		'it' => 'Azerbaigian',
		'hi' => 'अज़रबैजान',
	),
	'BA' => array(
		'en' => 'Bosnia and Herzegovina',
		'fr' => 'Bosnie-Herzégovine',
		'es' => 'Bosnia y Herzegovina',
		'it' => 'Bosnia ed Erzegovina',
		'hi' => 'बोस्निया और हर्जेगोविना',
	),
	'BB' => array(
		'en' => 'Barbados',
		'fr' => 'Barbade',
		'es' => 'Barbados',
		'it' => 'Barbados',
		'hi' => 'बारबाडोस',
	),
	'BD' => array(
		'en' => 'Bangladesh',
		'fr' => 'Bangladesh',
		'es' => 'Bangladesh',
		'it' => 'Bangladesh',
		'hi' => 'बांग्लादेश',
	),
	'BE' => array(
		'en' => 'Belgium',
		'fr' => 'Belgique',
		'es' => 'Bélgica',
		'it' => 'Belgio',
		'hi' => 'बेल्जियम',
	),
	'BF' => array(
		'en' => 'Burkina Faso',
		'fr' => 'Burkina Faso',
		'es' => 'Burkina Faso',
		'it' => 'Burkina Faso',
		'hi' => 'बुर्किना फासो',
	),
	'BG' => array(
		'en' => 'Bulgaria',
		'fr' => 'Bulgarie',
		'es' => 'Bulgaria',
		'it' => 'Bulgaria',
		'hi' => 'बुल्गारिया',
	),
	'BH' => array(
		'en' => 'Bahrain',
		'fr' => 'Bahreïn',
		'es' => 'Baréin',
		'it' => 'Bahrein',
		'hi' => 'बहरैन',
	),
	'BI' => array(
		'en' => 'Burundi',
		'fr' => 'Burundi',
		'es' => 'Burundi',
		'it' => 'Burundi',
		'hi' => 'बुरुंडी',
	),
	'BJ' => array(
		'en' => 'Benin',
		'fr' => 'Bénin',
		'es' => 'Benín',
		'it' => 'Benin',
		'hi' => 'बेनिन',
	),
	'BL' => array(
		'en' => 'Saint Barthélemy',
		'fr' => 'Saint-Barthélémy',
		'es' => 'San Bartolomé',
		'it' => 'Saint-Barthélemy',
		'hi' => 'सेंट बार्थेलेमी',
	),
	'BM' => array(
		'en' => 'Bermuda',
		'fr' => 'Bermudes',
		'es' => 'Bermudas',
		'it' => 'Bermuda',
		'hi' => 'बरमूडा',
	),
	'BN' => array(
		'en' => 'Brunei',
		'fr' => 'Brunéi Darussalam',
		'es' => 'Brunéi',
		'it' => 'Brunei',
		'hi' => 'ब्रुनेई',
	),
	'BO' => array(
		'en' => 'Bolivia',
		'fr' => 'Bolivie',
		'es' => 'Bolivia',
		'it' => 'Bolivia',
		'hi' => 'बोलीविया',
	),
	'BR' => array(
		'en' => 'Brazil',
		'fr' => 'Brésil',
		'es' => 'Brasil',
		'it' => 'Brasile',
		'hi' => 'ब्राज़ील',
	),
	'BS' => array(
		'en' => 'Bahamas',
		'fr' => 'Bahamas',
		'es' => 'Bahamas',
		'it' => 'Bahamas',
		'hi' => 'बहामास',
	),
	'BT' => array(
		'en' => 'Bhutan',
		'fr' => 'Bhoutan',
		'es' => 'Bután',
		'it' => 'Bhutan',
		'hi' => 'भूटान',
	),
	'BV' => array(
		'en' => 'Bouvet Island',
		'fr' => 'Île Bouvet',
		'es' => 'Isla Bouvet',
		'it' => 'Isola Bouvet',
		'hi' => 'बुवे द्वीप',
	),
	'BW' => array(
		'en' => 'Botswana',
		'fr' => 'Botswana',
		'es' => 'Botsuana',
		'it' => 'Botswana',
		'hi' => 'बोत्सवाना',
	),
	'BY' => array(
		'en' => 'Belarus',
		'fr' => 'Bélarus',
		'es' => 'Bielorrusia',
		'it' => 'Bielorussia',
		'hi' => 'बेलारूस',
	),
	'BZ' => array(
		'en' => 'Belize',
		'fr' => 'Belize',
		'es' => 'Belice',
		'it' => 'Belize',
		'hi' => 'बेलीज़',
	),
	'CA' => array(
		'en' => 'Canada',
		'fr' => 'Canada',
		'es' => 'Canadá',
		'it' => 'Canada',
		'hi' => 'कनाडा',
	),
	'CC' => array(
		'en' => 'Cocos [Keeling] Islands',
		'fr' => 'Îles Cocos - Keeling',
		'es' => 'Islas Cocos (Keeling)',
		'it' => 'Isole Cocos (Keeling)',
		'hi' => 'कोकोस (कीलिंग) द्वीपसमूह',
	),
	'CD' => array(
		'en' => 'Congo - Kinshasa',
		'fr' => 'République démocratique du Congo',
		'es' => 'República Democrática del Congo',
		'it' => 'Repubblica Democratica del Congo',
		'hi' => 'कांगो - किन्शासा',
	),
	'CF' => array(
		'en' => 'Central African Republic',
		'fr' => 'République centrafricaine',
		'es' => 'República Centroafricana',
		'it' => 'Repubblica Centrafricana',
		'hi' => 'मध्य अफ्रीकी गणराज्य',
	),
	'CG' => array(
		'en' => 'Congo - Brazzaville',
		'fr' => 'Congo',
		'es' => 'Congo',
		'it' => 'Congo',
		'hi' => 'कांगो - ब्राज़ाविले',
	),
	'CH' => array(
		'en' => 'Switzerland',
		'fr' => 'Suisse',
		'es' => 'Suiza',
		'it' => 'Svizzera',
		'hi' => 'स्विट्ज़रलैंड',
	),
	'CI' => array(
		'en' => 'Côte d’Ivoire',
		'fr' => 'Côte d’Ivoire',
		'es' => 'Costa de Marfil',
		'it' => "Costa d'Avorio",
		'hi' => 'कोट डी आइवर',
	),
	'CK' => array(
		'en' => 'Cook Islands',
		'fr' => 'Îles Cook',
		'es' => 'Islas Cook',
		'it' => 'Isole Cook',
		'hi' => 'कुक द्वीप समूह',
	),
	'CL' => array(
		'en' => 'Chile',
		'fr' => 'Chili',
		'es' => 'Chile',
		'it' => 'Cile',
		'hi' => 'चिली',
	),
	'CM' => array(
		'en' => 'Cameroon',
		'fr' => 'Cameroun',
		'es' => 'Camerún',
		'it' => 'Camerun',
		'hi' => 'कैमरून',
	),
	'CN' => array(
		'en' => 'China',
		'fr' => 'Chine',
		'es' => 'China',
		'it' => 'Cina',
		'hi' => 'चीन',
	),
	'CO' => array(
		'en' => 'Colombia',
		'fr' => 'Colombie',
		'es' => 'Colombia',
		'it' => 'Colombia',
		'hi' => 'कोलम्बिया',
	),
	'CR' => array(
		'en' => 'Costa Rica',
		'fr' => 'Costa Rica',
		'es' => 'Costa Rica',
		'it' => 'Costa Rica',
		'hi' => 'कोस्टा रिका',
	),
	'CU' => array(
		'en' => 'Cuba',
		'fr' => 'Cuba',
		'es' => 'Cuba',
		'it' => 'Cuba',
		'hi' => 'क्यूबा',
	),
	'CV' => array(
		'en' => 'Cape Verde',
		'fr' => 'Cap-Vert',
		'es' => 'Cabo Verde',
		'it' => 'Capo Verde',
		'hi' => 'केप वर्डे',
	),
	'CX' => array(
		'en' => 'Christmas Island',
		'fr' => 'Île Christmas',
		'es' => 'Isla Christmas',
		'it' => 'Isola Christmas',
		'hi' => 'क्रिसमस द्वीप',
	),
	'CY' => array(
		'en' => 'Cyprus',
		'fr' => 'Chypre',
		'es' => 'Chipre',
		'it' => 'Cipro',
		'hi' => 'साइप्रस',
	),
	'CZ' => array(
		'en' => 'Czech Republic',
		'fr' => 'République tchèque',
		'es' => 'República Checa',
		'it' => 'Repubblica Ceca',
		'hi' => 'चेक गणराज्य',
	),
	'DE' => array(
		'en' => 'Germany',
		'fr' => 'Allemagne',
		'es' => 'Alemania',
		'it' => 'Germania',
		'hi' => 'जर्मनी',
	),
	'DJ' => array(
		'en' => 'Djibouti',
		'fr' => 'Djibouti',
		'es' => 'Yibuti',
		'it' => 'Gibuti',
		'hi' => 'जिबूती',
	),
	'DK' => array(
		'en' => 'Denmark',
		'fr' => 'Danemark',
		'es' => 'Dinamarca',
		'it' => 'Danimarca',
		'hi' => 'डेनमार्क',
	),
	'DM' => array(
		'en' => 'Dominica',
		'fr' => 'Dominique',
		'es' => 'Dominica',
		'it' => 'Dominica',
		'hi' => 'डोमिनिका',
	),
	'DO' => array(
		'en' => 'Dominican Republic',
		'fr' => 'République dominicaine',
		'es' => 'República Dominicana',
		'it' => 'Repubblica Dominicana',
		'hi' => 'डोमिनिकन गणराज्य',
	),
	'DZ' => array(
		'en' => 'Algeria',
		'fr' => 'Algérie',
		'es' => 'Argelia',
		'it' => 'Algeria',
		'hi' => 'अल्जीरिया',
	),
	'EC' => array(
		'en' => 'Ecuador',
		'fr' => 'Équateur',
		'es' => 'Ecuador',
		'it' => 'Ecuador',
		'hi' => 'इक्वाडोर',
	),
	'EE' => array(
		'en' => 'Estonia',
		'fr' => 'Estonie',
		'es' => 'Estonia',
		'it' => 'Estonia',
		'hi' => 'एस्टोनिया',
	),
	'EG' => array(
		'en' => 'Egypt',
		'fr' => 'Égypte',
		'es' => 'Egipto',
		'it' => 'Egitto',
		'hi' => 'मिस्र',
	),
	'ER' => array(
		'en' => 'Eritrea',
		'fr' => 'Érythrée',
		'es' => 'Eritrea',
		'it' => 'Eritrea',
		'hi' => 'इरिट्रिया',
	),
	'ES' => array(
		'en' => 'Spain',
		'fr' => 'Espagne',
		'es' => 'España',
		'it' => 'Spagna',
		'hi' => 'स्पेन',
	),
	'ET' => array(
		'en' => 'Ethiopia',
		'fr' => 'Éthiopie',
		'es' => 'Etiopía',
		'it' => 'Etiopia',
		'hi' => 'इथियोपिया',
	),
	'FI' => array(
		'en' => 'Finland',
		'fr' => 'Finlande',
		'es' => 'Finlandia',
		'it' => 'Finlandia',
		'hi' => 'फिनलैंड',
	),
	'FJ' => array(
		'en' => 'Fiji',
		'fr' => 'Fidji',
		'es' => 'Fiyi',
		'it' => 'Figi',
		'hi' => 'फिजी',
	),
	'FK' => array(
		'en' => 'Falkland Islands',
		'fr' => 'Îles Malouines',
		'es' => 'Islas Malvinas',
		'it' => 'Isole Falkland',
		'hi' => 'फ़ॉकलैंड द्वीपसमूह',
	),
	'FM' => array(
		'en' => 'Micronesia',
		'fr' => 'États fédérés de Micronésie',
		'es' => 'Micronesia',
		'it' => 'Micronesia',
		'hi' => 'माइक्रोनेशिया',
	),
	'FO' => array(
		'en' => 'Faroe Islands',
		'fr' => 'Îles Féroé',
		'es' => 'Islas Feroe',
		'it' => 'Isole Faroe',
		'hi' => 'फैरो द्वीप',
	),
	'FR' => array(
		'en' => 'France',
		'fr' => 'France',
		'es' => 'Francia',
		'it' => 'Francia',
		'hi' => 'फ्रांस',
	),
	'GA' => array(
		'en' => 'Gabon',
		'fr' => 'Gabon',
		'es' => 'Gabón',
		'it' => 'Gabon',
		'hi' => 'गैबॉन',
	),
	'GB' => array(
		'en' => 'United Kingdom',
		'fr' => 'Royaume-Uni',
		'es' => 'Reino Unido',
		'it' => 'Regno Unito',
		'hi' => 'यूनाइटेड किंगडम',
	),
	'GD' => array(
		'en' => 'Grenada',
		'fr' => 'Grenade',
		'es' => 'Granada',
		'it' => 'Grenada',
		'hi' => 'ग्रेनाडा',
	),
	'GE' => array(
		'en' => 'Georgia',
		'fr' => 'Géorgie',
		'es' => 'Georgia',
		'it' => 'Georgia',
		'hi' => 'जॉर्जिया',
	),
	'GF' => array(
		'en' => 'French Guiana',
		'fr' => 'Guyane française',
		'es' => 'Guayana Francesa',
		'it' => 'Guyana Francese',
		'hi' => 'फ्रेंच गुयाना',
	),
	'GG' => array(
		'en' => 'Guernsey',
		'fr' => 'Guernesey',
		'es' => 'Guernsey',
		'it' => 'Guernsey',
		'hi' => 'गर्नज़ी',
	),
	'GH' => array(
		'en' => 'Ghana',
		'fr' => 'Ghana',
		'es' => 'Ghana',
		'it' => 'Ghana',
		'hi' => 'घाना',
	),
	'GI' => array(
		'en' => 'Gibraltar',
		'fr' => 'Gibraltar',
		'es' => 'Gibraltar',
		'it' => 'Gibilterra',
		'hi' => 'जिब्राल्टर',
	),
	'GL' => array(
		'en' => 'Greenland',
		'fr' => 'Groenland',
		'es' => 'Groenlandia',
		'it' => 'Groenlandia',
		'hi' => 'ग्रीनलैंड',
	),
	'GM' => array(
		'en' => 'Gambia',
		'fr' => 'Gambie',
		'es' => 'Gambia',
		'it' => 'Gambia',
		'hi' => 'गाम्बिया',
	),
	'GN' => array(
		'en' => 'Guinea',
		'fr' => 'Guinée',
		'es' => 'Guinea',
		'it' => 'Guinea',
		'hi' => 'गिनिया',
	),
	'GP' => array(
		'en' => 'Guadeloupe',
		'fr' => 'Guadeloupe',
		'es' => 'Guadalupe',
		'it' => ' Guadalupa',
		'hi' => 'ग्वाडेलूप',
	),
	'GQ' => array(
		'en' => 'Equatorial Guinea',
		'fr' => 'Guinée équatoriale',
		'es' => 'Guinea Ecuatorial',
		'it' => 'Guinea Equatoriale',
		'hi' => 'इक्वेटोरियल गिनी',
	),
	'GR' => array(
		'en' => 'Greece',
		'fr' => 'Grèce',
		'es' => 'Grecia',
		'it' => 'Grecia',
		'hi' => 'यूनान',
	),
	'GS' => array(
		'en' => 'South Georgia and the South Sandwich Islands',
		'fr' => 'Géorgie du Sud et les îles Sandwich du Sud',
		'es' => 'Georgia del Sur y las Islas Sandwich del Sur',
		'it' => 'Georgia del Sud e Isole Sandwich Meridionali',
		'hi' => 'दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीपसमूह',
	),
	'GT' => array(
		'en' => 'Guatemala',
		'fr' => 'Guatemala',
		'es' => 'Guatemala',
		'it' => 'Guatemala',
		'hi' => 'ग्वाटेमाला',
	),
	'GU' => array(
		'en' => 'Guam',
		'fr' => 'Guam',
		'es' => 'Guam',
		'it' => 'Guam',
		'hi' => 'गुआम',
	),
	'GW' => array(
		'en' => 'Guinea-Bissau',
		'fr' => 'Guinée-Bissau',
		'es' => 'Guinea-Bisáu',
		'it' => 'Guinea-Bissau',
		'hi' => 'गिनी-बिसाउ',
	),
	'GY' => array(
		'en' => 'Guyana',
		'fr' => 'Guyana',
		'es' => 'Guyana',
		'it' => 'Guyana',
		'hi' => 'गुयाना',
	),
	'HK' => array(
		'en' => 'Hong Kong SAR China',
		'fr' => 'R.A.S. chinoise de Hong Kong',
		'es' => 'RAE de Hong Kong (China)',
		'it' => 'RAE di Hong Kong (Cina)',
		'hi' => 'हांगकांग',
	),
	'HM' => array(
		'en' => 'Heard Island and McDonald Islands',
		'fr' => 'Îles Heard et MacDonald',
		'es' => 'Islas Heard y McDonald',
		'it' => 'Isole Heard e McDonald',
		'hi' => 'हर्ड और मैकडोनाल्ड द्वीप',
	),
	'HN' => array(
		'en' => 'Honduras',
		'fr' => 'Honduras',
		'es' => 'Honduras',
		'it' => 'Honduras',
		'hi' => 'होंडुरास',
	),
	'HR' => array(
		'en' => 'Croatia',
		'fr' => 'Croatie',
		'es' => 'Croacia',
		'it' => 'Croazia',
		'hi' => 'क्रोएशिया',
	),
	'HT' => array(
		'en' => 'Haiti',
		'fr' => 'Haïti',
		'es' => 'Haití',
		'it' => 'Haiti',
		'hi' => 'हैती',
	),
	'HU' => array(
		'en' => 'Hungary',
		'fr' => 'Hongrie',
		'es' => 'Hungría',
		'it' => 'Ungheria',
		'hi' => 'हंगरी',
	),
	'ID' => array(
		'en' => 'Indonesia',
		'fr' => 'Indonésie',
		'es' => 'Indonesia',
		'it' => 'Indonesia',
		'hi' => 'इंडोनेशिया',
	),
	'IE' => array(
		'en' => 'Ireland',
		'fr' => 'Irlande',
		'es' => 'Irlanda',
		'it' => 'Irlanda',
		'hi' => 'आयरलैंड',
	),
	'IL' => array(
		'en' => 'Israel',
		'fr' => 'Israël',
		'es' => 'Israel',
		'it' => 'Israele',
		'hi' => 'इज़राइल',
	),
	'IM' => array(
		'en' => 'Isle of Man',
		'fr' => 'Île de Man',
		'es' => 'Isla de Man',
		'it' => 'Isola di Man',
		'hi' => 'आइल ऑफ़ मैन',
	),
	'IN' => array(
		'en' => 'India',
		'fr' => 'Inde',
		'es' => 'India',
		'it' => 'India',
		'hi' => 'भारत',
	),
	'IO' => array(
		'en' => 'British Indian Ocean Territory',
		'fr' => 'Territoire britannique de l\'océan Indien',
		'es' => 'Territorio Británico del Océano Índico',
		'it' => "Territorio Britannico dell'Oceano Indiano",
		'hi' => 'ब्रिटिश भारतीय महासागर क्षेत्र',
	),
	'IQ' => array(
		'en' => 'Iraq',
		'fr' => 'Irak',
		'es' => 'Irak',
		'it' => 'Iraq',
		'hi' => 'इराक',
	),
	'IR' => array(
		'en' => 'Iran',
		'fr' => 'Iran',
		'es' => 'Irán',
		'it' => 'Iran',
		'hi' => 'ईरान',
	),
	'IS' => array(
		'en' => 'Iceland',
		'fr' => 'Islande',
		'es' => 'Islandia',
		'it' => 'Islanda',
		'hi' => 'आइसलैंड',
	),
	'IT' => array(
		'en' => 'Italy',
		'fr' => 'Italie',
		'es' => 'Italia',
		'it' => 'Italia',
		'hi' => 'इटली',
	),
	'JE' => array(
		'en' => 'Jersey',
		'fr' => 'Jersey',
		'es' => 'Jersey',
		'it' => 'Jersey',
		'hi' => 'जरसी',
	),
	'JM' => array(
		'en' => 'Jamaica',
		'fr' => 'Jamaïque',
		'es' => 'Jamaica',
		'it' => 'Giamaica',
		'hi' => 'जमैका',
	),
	'JO' => array(
		'en' => 'Jordan',
		'fr' => 'Jordanie',
		'es' => 'Jordania',
		'it' => 'Giordania',
		'hi' => 'जॉर्डन',
	),
	'JP' => array(
		'en' => 'Japan',
		'fr' => 'Japon',
		'es' => 'Japón',
		'it' => 'Giappone',
		'hi' => 'जापान',
	),
	'KE' => array(
		'en' => 'Kenya',
		'fr' => 'Kenya',
		'es' => 'Kenia',
		'it' => 'Kenya',
		'hi' => 'केन्या',
	),
	'KG' => array(
		'en' => 'Kyrgyzstan',
		'fr' => 'Kirghizistan',
		'es' => 'Kirguistán',
		'it' => 'Kirghizistan',
		'hi' => 'किर्गिज़स्तान',
	),
	'KH' => array(
		'en' => 'Cambodia',
		'fr' => 'Cambodge',
		'es' => 'Camboya',
		'it' => 'Cambogia',
		'hi' => 'कंबोडिया',
	),
	'KI' => array(
		'en' => 'Kiribati',
		'fr' => 'Kiribati',
		'es' => 'Kiribati',
		'it' => 'Kiribati',
		'hi' => 'किरिबाती',
	),
	'KM' => array(
		'en' => 'Comoros',
		'fr' => 'Comores',
		'es' => 'Comoras',
		'it' => 'Comore',
		'hi' => 'कोमोरोस',
	),
	'KN' => array(
		'en' => 'Saint Kitts and Nevis',
		'fr' => 'Saint-Kitts-et-Nevis',
		'es' => 'San Cristóbal y Nieves',
		'it' => 'Saint Kitts e Nevis',
		'hi' => 'सेंट किट्स और नेविस',
	),
	'KP' => array(
		'en' => 'North Korea',
		'fr' => 'Corée du Nord',
		'es' => 'Corea del Norte',
		'it' => 'Corea del Nord',
		'hi' => 'उत्तरी कोरिया',
	),
	'KR' => array(
		'en' => 'South Korea',
		'fr' => 'Corée du Sud',
		'es' => 'Corea del Sur',
		'it' => 'Corea del Sud',
		'hi' => 'दक्षिण कोरिया',
	),
	'KW' => array(
		'en' => 'Kuwait',
		'fr' => 'Koweït',
		'es' => 'Kuwait',
		'it' => 'Kuwait',
		'hi' => 'कुवैत',
	),
	'KY' => array(
		'en' => 'Cayman Islands',
		'fr' => 'Îles Caïmans',
		'es' => 'Islas Caimán',
		'it' => 'Isole Cayman',
		'hi' => 'केमैन द्वीप समूह',
	),
	'KZ' => array(
		'en' => 'Kazakhstan',
		'fr' => 'Kazakhstan',
		'es' => 'Kazajistán',
		'it' => 'Kazakistan',
		'hi' => 'कज़ाक़िस्तान',
	),
	'LA' => array(
		'en' => 'Laos',
		'fr' => 'Laos',
		'es' => 'Laos',
		'it' => 'Laos',
		'hi' => 'लाओस',
	),
	'LB' => array(
		'en' => 'Lebanon',
		'fr' => 'Liban',
		'es' => 'Líbano',
		'it' => 'Libano',
		'hi' => 'लेबनान',
	),
	'LC' => array(
		'en' => 'Saint Lucia',
		'fr' => 'Sainte-Lucie',
		'es' => 'Santa Lucía',
		'it' => 'Santa Lucia',
		'hi' => 'सेंट लूसिया',
	),
	'LI' => array(
		'en' => 'Liechtenstein',
		'fr' => 'Liechtenstein',
		'es' => 'Liechtenstein',
		'it' => 'Liechtenstein',
		'hi' => 'लिकटेंस्टीन',
	),
	'LK' => array(
		'en' => 'Sri Lanka',
		'fr' => 'Sri Lanka',
		'es' => 'Sri Lanka',
		'it' => 'Sri Lanka',
		'hi' => 'श्रीलंका',
	),
	'LR' => array(
		'en' => 'Liberia',
		'fr' => 'Libéria',
		'es' => 'Liberia',
		'it' => 'Liberia',
		'hi' => 'लाइबेरिया',
	),
	'LS' => array(
		'en' => 'Lesotho',
		'fr' => 'Lesotho',
		'es' => 'Lesoto',
		'it' => 'Lesotho',
		'hi' => 'लेसोथो',
	),
	'LT' => array(
		'en' => 'Lithuania',
		'fr' => 'Lituanie',
		'es' => 'Lituania',
		'it' => 'Lituania',
		'hi' => 'लिथुआनिया',
	),
	'LU' => array(
		'en' => 'Luxembourg',
		'fr' => 'Luxembourg',
		'es' => 'Luxemburgo',
		'it' => 'Lussemburgo',
		'hi' => 'लक्ज़मबर्ग',
	),
	'LV' => array(
		'en' => 'Latvia',
		'fr' => 'Lettonie',
		'es' => 'Letonia',
		'it' => 'Lettonia',
		'hi' => 'लातविया',
	),
	'LY' => array(
		'en' => 'Libya',
		'fr' => 'Libye',
		'es' => 'Libia',
		'it' => 'Libia',
		'hi' => 'लीबिया',
	),
	'MA' => array(
		'en' => 'Morocco',
		'fr' => 'Maroc',
		'es' => 'Marruecos',
		'it' => 'Marocco',
		'hi' => 'मोरक्को',
	),
	'MC' => array(
		'en' => 'Monaco',
		'fr' => 'Monaco',
		'es' => 'Mónaco',
		'it' => 'Monaco',
		'hi' => 'मोनाको',
	),
	'MD' => array(
		'en' => 'Moldova',
		'fr' => 'Moldavie',
		'es' => 'Moldavia',
		'it' => 'Moldavia',
		'hi' => 'मोल्दोवा',
	),
	'ME' => array(
		'en' => 'Montenegro',
		'fr' => 'Monténégro',
		'es' => 'Montenegro',
		'it' => 'Montenegro',
		'hi' => 'मोंटेनेग्रो',
	),
	'MF' => array(
		'en' => 'Saint Martin',
		'fr' => 'Saint-Martin',
		'es' => 'San Martín',
		'it' => 'Saint-Martin',
		'hi' => 'सेंट मार्टिन',
	),
	'MG' => array(
		'en' => 'Madagascar',
		'fr' => 'Madagascar',
		'es' => 'Madagascar',
		'it' => 'Madagascar',
		'hi' => 'मेडागास्कर',
	),
	'MH' => array(
		'en' => 'Marshall Islands',
		'fr' => 'Îles Marshall',
		'es' => 'Islas Marshall',
		'it' => 'Isole Marshall',
		'hi' => 'मार्शल द्वीपसमूह',
	),
	'MK' => array(
		'en' => 'Macedonia',
		'fr' => 'Macédoine',
		'es' => 'Macedonia del Norte',
		'it' => 'Macedonia',
		'hi' => 'मैसेडोनिया',
	),
	'ML' => array(
		'en' => 'Mali',
		'fr' => 'Mali',
		'es' => 'Malí',
		'it' => 'Mali',
		'hi' => 'माली',
	),
	'MM' => array(
		'en' => 'Myanmar [Burma]',
		'fr' => 'Myanmar',
		'es' => 'Myanmar',
		'it' => 'Myanmar',
		'hi' => 'म्यांमार [बर्मा]',
	),
	'MN' => array(
		'en' => 'Mongolia',
		'fr' => 'Mongolie',
		'es' => 'Mongolia',
		'it' => 'Mongolia',
		'hi' => 'मंगोलिया',
	),
	'MO' => array(
		'en' => 'Macau SAR China',
		'fr' => 'R.A.S. chinoise de Macao',
		'es' => 'R.A.E. de Macao (China)',
		'it' => 'RAS di Macao (Cina)',
		'hi' => 'मकाऊ (चीन विशेष प्रशासनिक क्षेत्र)',
	),
	'MP' => array(
		'en' => 'Northern Mariana Islands',
		'fr' => 'Îles Mariannes du Nord',
		'es' => 'Islas Marianas del Norte',
		'it' => 'Isole Marianne Settentrionali',
		'hi' => 'नॉर्दर्न मरिआना द्वीपसमूह',
	),
	'MQ' => array(
		'en' => 'Martinique',
		'fr' => 'Martinique',
		'es' => 'Martinica',
		'it' => 'Martinica',
		'hi' => 'मार्टीनिक',
	),
	'MR' => array(
		'en' => 'Mauritania',
		'fr' => 'Mauritanie',
		'es' => 'Mauritania',
		'it' => 'Mauritania',
		'hi' => 'मौरीतानिया',
	),
	'MS' => array(
		'en' => 'Montserrat',
		'fr' => 'Montserrat',
		'es' => 'Montserrat',
		'it' => 'Montserrat',
		'hi' => 'मॉन्टसेरात',
	),
	'MT' => array(
		'en' => 'Malta',
		'fr' => 'Malte',
		'es' => 'Malta',
		'it' => 'Malta',
		'hi' => 'माल्टा',
	),
	'MU' => array(
		'en' => 'Mauritius',
		'fr' => 'Maurice',
		'es' => 'Mauricio',
		'it' => 'Mauritius',
		'hi' => 'मॉरीशस',
	),
	'MV' => array(
		'en' => 'Maldives',
		'fr' => 'Maldives',
		'es' => 'Maldivas',
		'it' => 'Maldive',
		'hi' => 'मालदीव',
	),
	'MW' => array(
		'en' => 'Malawi',
		'fr' => 'Malawi',
		'es' => 'Malaui',
		'it' => 'Malawi',
		'hi' => 'मलावी',
	),
	'MX' => array(
		'en' => 'Mexico',
		'fr' => 'Mexique',
		'es' => 'México',
		'it' => 'Messico',
		'hi' => 'मेक्सिको',
	),
	'MY' => array(
		'en' => 'Malaysia',
		'fr' => 'Malaisie',
		'es' => 'Malasia',
		'it' => 'Malesia',
		'hi' => 'मलेशिया',
	),
	'MZ' => array(
		'en' => 'Mozambique',
		'fr' => 'Mozambique',
		'es' => 'Mozambique',
		'it' => 'Mozambico',
		'hi' => 'मोज़ाम्बिक',
	),
	'NA' => array(
		'en' => 'Namibia',
		'fr' => 'Namibie',
		'es' => 'Namibia',
		'it' => 'Namibia',
		'hi' => 'नामिबिया',
	),
	'NC' => array(
		'en' => 'New Caledonia',
		'fr' => 'Nouvelle-Calédonie',
		'es' => 'Nueva Caledonia',
		'it' => 'Nuova Caledonia',
		'hi' => 'न्यू कैलेडोनिया',
	),
	'NE' => array(
		'en' => 'Niger',
		'fr' => 'Niger',
		'es' => 'Níger',
		'it' => 'Niger',
		'hi' => 'नाइजर',
	),
	'NF' => array(
		'en' => 'Norfolk Island',
		'fr' => 'Île Norfolk',
		'es' => 'Isla Norfolk',
		'it' => 'Isola Norfolk',
		'hi' => 'नॉरफ़ॉल्क द्वीप',
	),
	'NG' => array(
		'en' => 'Nigeria',
		'fr' => 'Nigéria',
		'es' => 'Nigeria',
		'it' => 'Nigeria',
		'hi' => 'नाइजीरिया',
	),
	'NI' => array(
		'en' => 'Nicaragua',
		'fr' => 'Nicaragua',
		'es' => 'Nicaragua',
		'it' => 'Nicaragua',
		'hi' => 'निकारागुआ',
	),
	'NL' => array(
		'en' => 'Netherlands',
		'fr' => 'Pays-Bas',
		'es' => 'Países Bajos',
		'it' => 'Paesi Bassi',
		'hi' => 'नीदरलैंड',
	),
	'NO' => array(
		'en' => 'Norway',
		'fr' => 'Norvège',
		'es' => 'Noruega',
		'it' => 'Norvegia',
		'hi' => 'नॉर्वे',
	),
	'NP' => array(
		'en' => 'Nepal',
		'fr' => 'Népal',
		'es' => 'Nepal',
		'it' => 'Nepal',
		'hi' => 'नेपाल',
	),
	'NR' => array(
		'en' => 'Nauru',
		'fr' => 'Nauru',
		'es' => 'Nauru',
		'it' => 'Nauru',
		'hi' => 'नाउरु',
	),
	'NU' => array(
		'en' => 'Niue',
		'fr' => 'Niue',
		'es' => 'Niue',
		'it' => 'Niue',
		'hi' => 'निउए',
	),
	'NZ' => array(
		'en' => 'New Zealand',
		'fr' => 'Nouvelle-Zélande',
		'es' => 'Nueva Zelanda',
		'it' => 'Nuova Zelanda',
		'hi' => 'न्यूज़ीलैंड',
	),
	'OM' => array(
		'en' => 'Oman',
		'fr' => 'Oman',
		'es' => 'Omán',
		'it' => 'Oman',
		'hi' => 'ओमान',
	),
	'PA' => array(
		'en' => 'Panama',
		'fr' => 'Panama',
		'es' => 'Panamá',
		'it' => 'Panama',
		'hi' => 'पनामा',
	),
	'PE' => array(
		'en' => 'Peru',
		'fr' => 'Pérou',
		'es' => 'Perú',
		'it' => 'Perù',
		'hi' => 'पेरू',
	),
	'PF' => array(
		'en' => 'French Polynesia',
		'fr' => 'Polynésie française',
		'es' => 'Polinesia Francesa',
		'it' => 'Polinesia Francese',
		'hi' => 'फ्रेंच पॉलिनेशिया',
	),
	'PG' => array(
		'en' => 'Papua New Guinea',
		'fr' => 'Papouasie-Nouvelle-Guinée',
		'es' => 'Papúa Nueva Guinea',
		'it' => 'Papua Nuova Guinea',
		'hi' => 'पापुआ न्यू गिनी',
	),
	'PH' => array(
		'en' => 'Philippines',
		'fr' => 'Philippines',
		'es' => 'Filipinas',
		'it' => 'Filippine',
		'hi' => 'फिलिपींस',
	),
	'PK' => array(
		'en' => 'Pakistan',
		'fr' => 'Pakistan',
		'es' => 'Pakistán',
		'it' => 'Pakistan',
		'hi' => 'पाकिस्तान',
	),
	'PL' => array(
		'en' => 'Poland',
		'fr' => 'Pologne',
		'es' => 'Polonia',
		'it' => 'Polonia',
		'hi' => 'पोलैंड',
	),
	'PM' => array(
		'en' => 'Saint Pierre and Miquelon',
		'fr' => 'Saint-Pierre-et-Miquelon',
		'es' => 'San Pedro y Miquelón',
		'it' => 'Saint-Pierre e Miquelon',
		'hi' => 'सेंट पियरे और मिकेलोन',
	),
	'PN' => array(
		'en' => 'Pitcairn Islands',
		'fr' => 'Pitcairn',
		'es' => 'Islas Pitcairn',
		'it' => 'Isole Pitcairn',
		'hi' => 'पिटकैर्न द्वीपसमूह',
	),
	'PR' => array(
		'en' => 'Puerto Rico',
		'fr' => 'Porto Rico',
		'es' => 'Puerto Rico',
		'it' => 'Porto Rico',
		'hi' => 'प्यूर्टो रिको',
	),
	'PS' => array(
		'en' => 'Palestinian Territories',
		'fr' => 'Territoire palestinien',
		'es' => 'Territorios Palestinos',
		'it' => 'Territori Palestinesi',
		'hi' => 'फلسطीनी क्षेत्र',
	),
	'PT' => array(
		'en' => 'Portugal',
		'fr' => 'Portugal',
		'es' => 'Portugal',
		'it' => 'Portogallo',
		'hi' => 'पुर्तगाल',
	),
	'PW' => array(
		'en' => 'Palau',
		'fr' => 'Palaos',
		'es' => 'Palaos',
		'it' => 'Palau',
		'hi' => 'पलाऊ',
	),
	'PY' => array(
		'en' => 'Paraguay',
		'fr' => 'Paraguay',
		'es' => 'Paraguay',
		'it' => 'Paraguay',
		'hi' => 'पैराग्वे',
	),
	'QA' => array(
		'en' => 'Qatar',
		'fr' => 'Qatar',
		'es' => 'Catar',
		'it' => 'Qatar',
		'hi' => 'कतार',
	),
	'RE' => array(
		'en' => 'Réunion',
		'fr' => 'Réunion',
		'es' => 'Reunión',
		'it' => 'Riunione',
		'hi' => 'रिउनियन',
	),
	'RO' => array(
		'en' => 'Romania',
		'fr' => 'Roumanie',
		'es' => 'Rumanía',
		'it' => 'Romania',
		'hi' => 'रोमानिया',
	),
	'RS' => array(
		'en' => 'Serbia',
		'fr' => 'Serbie',
		'es' => 'Serbia',
		'it' => 'Serbia',
		'hi' => 'सर्बिया',
	),
	'RU' => array(
		'en' => 'Russia',
		'fr' => 'Russie',
		'es' => 'Rusia',
		'it' => 'Russia',
		'hi' => 'रूस',
	),
	'RW' => array(
		'en' => 'Rwanda',
		'fr' => 'Rwanda',
		'es' => 'Ruanda',
		'it' => 'Ruanda',
		'hi' => 'रवांडा',
	),
	'SA' => array(
		'en' => 'Saudi Arabia',
		'fr' => 'Arabie saoudite',
		'es' => 'Arabia Saudita',
		'it' => 'Arabia Saudita',
		'hi' => 'साउदी अरब',
	),
	'SB' => array(
		'en' => 'Solomon Islands',
		'fr' => 'Îles Salomon',
		'es' => 'Islas Salomón',
		'it' => 'Isole Salomone',
		'hi' => 'सोलोमन द्वीपसमूह',
	),
	'SC' => array(
		'en' => 'Seychelles',
		'fr' => 'Seychelles',
		'es' => 'Seychelles',
		'it' => 'Seychelles',
		'hi' => 'सेशेल्स',
	),
	'SD' => array(
		'en' => 'Sudan',
		'fr' => 'Soudan',
		'es' => 'Sudán',
		'it' => 'Sudan',
		'hi' => 'सूडान',
	),
	'SE' => array(
		'en' => 'Sweden',
		'fr' => 'Suède',
		'es' => 'Suecia',
		'it' => 'Svezia',
		'hi' => 'स्वीडन',
	),
	'SG' => array(
		'en' => 'Singapore',
		'fr' => 'Singapour',
		'es' => 'Singapur',
		'it' => 'Singapore',
		'hi' => 'सिंगापुर',
	),
	'SH' => array(
		'en' => 'Saint Helena',
		'fr' => 'Sainte-Hélène',
		'es' => 'Santa Elena',
		'it' => 'Sant\'Elena',
		'hi' => 'सेंट हेलेना',
	),
	'SI' => array(
		'en' => 'Slovenia',
		'fr' => 'Slovénie',
		'es' => 'Eslovenia',
		'it' => 'Slovenia',
		'hi' => 'स्लोवेनिया',
	),
	'SJ' => array(
		'en' => 'Svalbard and Jan Mayen',
		'fr' => 'Svalbard et Île Jan Mayen',
		'es' => 'Svalbard y Jan Mayen',
		'it' => 'Svalbard e Jan Mayen',
		'hi' => 'स्वालबार्ड और जान मायेन',
	),
	'SK' => array(
		'en' => 'Slovakia',
		'fr' => 'Slovaquie',
		'es' => 'Eslovaquia',
		'it' => 'Slovacchia',
		'hi' => 'स्लोवाकिया',
	),
	'SL' => array(
		'en' => 'Sierra Leone',
		'fr' => 'Sierra Leone',
		'es' => 'Sierra Leona',
		'it' => 'Sierra Leone',
		'hi' => 'सिएरा लियोन',
	),
	'SM' => array(
		'en' => 'San Marino',
		'fr' => 'Saint-Marin',
		'es' => 'San Marino',
		'it' => 'San Marino',
		'hi' => 'सान मैरिनो',
	),
	'SN' => array(
		'en' => 'Senegal',
		'fr' => 'Sénégal',
		'es' => 'Senegal',
		'it' => 'Senegal',
		'hi' => 'सेनेगल',
	),
	'SO' => array(
		'en' => 'Somalia',
		'fr' => 'Somalie',
		'es' => 'Somalia',
		'it' => 'Somalia',
		'hi' => 'सोमैरिया',
	),
	'SR' => array(
		'en' => 'Suriname',
		'fr' => 'Suriname',
		'es' => 'Surinam',
		'it' => 'Suriname',
		'hi' => 'सुरिनाम',
	),
	'ST' => array(
		'en' => 'São Tomé and Príncipe',
		'fr' => 'Sao Tomé-et-Principe',
		'es' => 'Santo Tomé y Príncipe',
		'it' => 'São Tomé e Príncipe',
		'hi' => 'साओ टोमे और प्रिंसिपे',
	),
	'SV' => array(
		'en' => 'El Salvador',
		'fr' => 'El Salvador',
		'es' => 'El Salvador',
		'it' => 'El Salvador',
		'hi' => 'एल साल्वाडोर',
	),
	'SY' => array(
		'en' => 'Syria',
		'fr' => 'Syrie',
		'es' => 'Siria',
		'it' => 'Siria',
		'hi' => 'सीरिया',
	),
	'SZ' => array(
		'en' => 'Swaziland',
		'fr' => 'Swaziland',
		'es' => 'Esuatini',
		'it' => 'Swaziland',
		'hi' => 'स्वाज़ीलैंड',
	),
	'TC' => array(
		'en' => 'Turks and Caicos Islands',
		'fr' => 'Îles Turks et Caïques',
		'es' => 'Islas Turcas y Caicos',
		'it' => 'Isole Turks e Caicos',
		'hi' => 'टर्क्स और कैकोस द्वीपसमूह',
	),
	'TD' => array(
		'en' => 'Chad',
		'fr' => 'Tchad',
		'es' => 'Chad',
		'it' => 'Ciad',
		'hi' => 'चाड',
	),
	'TF' => array(
		'en' => 'French Southern Territories',
		'fr' => 'Terres australes françaises',
		'es' => 'Territorios Australes Franceses',
		'it' => 'Territori francesi meridionali e antartici',
		'hi' => 'फ्रेंच दक्षिणी क्षेत्र',
	),
	'TG' => array(
		'en' => 'Togo',
		'fr' => 'Togo',
		'es' => 'Togo',
		'it' => 'Togo',
		'hi' => 'टोगो',
	),
	'TH' => array(
		'en' => 'Thailand',
		'fr' => 'Thaïlande',
		'es' => 'Tailandia',
		'it' => 'Thailandia',
		'hi' => 'थाईलैंड',
	),
	'TJ' => array(
		'en' => 'Tajikistan',
		'fr' => 'Tadjikistan',
		'es' => 'Tayikistán',
		'it' => 'Tagikistan',
		'hi' => 'ताजिकिस्तान',
	),
	'TK' => array(
		'en' => 'Tokelau',
		'fr' => 'Tokelau',
		'es' => 'Tokelau',
		'it' => 'Tokelau',
		'hi' => 'टोकेलाऊ',
	),
	'TL' => array(
		'en' => 'Timor-Leste',
		'fr' => 'Timor oriental',
		'es' => 'Timor-Leste',
		'it' => 'Timor Est',
		'hi' => 'तीमोर-लेस्ते',
	),
	'TM' => array(
		'en' => 'Turkmenistan',
		'fr' => 'Turkménistan',
		'es' => 'Turkmenistán',
		'it' => 'Turkmenistan',
		'hi' => 'तुर्कमेनिस्तान',
	),
	'TN' => array(
		'en' => 'Tunisia',
		'fr' => 'Tunisie',
		'es' => 'Túnez',
		'it' => 'Tunisia',
		'hi' => 'ट्यूनीशिया',
	),
	'TO' => array(
		'en' => 'Tonga',
		'fr' => 'Tonga',
		'es' => 'Tonga',
		'it' => 'Tonga',
		'hi' => 'टोंगा',
	),
	'TR' => array(
		'en' => 'Turkey',
		'fr' => 'Turquie',
		'es' => 'Turquía',
		'it' => 'Turchia',
		'hi' => 'तुर्की',
	),
	'TT' => array(
		'en' => 'Trinidad and Tobago',
		'fr' => 'Trinité-et-Tobago',
		'es' => 'Trinidad y Tobago',
		'it' => 'Trinidad e Tobago',
		'hi' => 'त्रिनिदाद और टोबैगो',
	),
	'TV' => array(
		'en' => 'Tuvalu',
		'fr' => 'Tuvalu',
		'es' => 'Tuvalu',
		'it' => 'Tuvalu',
		'hi' => 'तुवालु',
	),
	'TW' => array(
		'en' => 'Taiwan',
		'fr' => 'Taïwan',
		'es' => 'Taiwán',
		'it' => 'Taiwan',
		'hi' => 'ताइवान',
	),
	'TZ' => array(
		'en' => 'Tanzania',
		'fr' => 'Tanzanie',
		'es' => 'Tanzania',
		'it' => 'Tanzania',
		'hi' => 'तंजानिया',
	),
	'UA' => array(
		'en' => 'Ukraine',
		'fr' => 'Ukraine',
		'es' => 'Ucrania',
		'it' => 'Ucraina',
		'hi' => 'यूक्रेन',
	),
	'UG' => array(
		'en' => 'Uganda',
		'fr' => 'Ouganda',
		'es' => 'Uganda',
		'it' => 'Uganda',
		'hi' => 'युगांडा',
	),
	'UM' => array(
		'en' => 'U.S. Minor Outlying Islands',
		'fr' => 'Îles Mineures Éloignées des États-Unis',
		'es' => 'Islas Ultramarinas Menores de EE. UU.',
		'it' => 'Isole Minori Esterne degli Stati Uniti',
		'hi' => 'यू.एस. छोटे दूरस्थ द्वीप',
	),
	'US' => array(
		'en' => 'United States',
		'fr' => 'États-Unis',
		'es' => 'Estados Unidos',
		'it' => 'Stati Uniti',
		'hi' => 'संयुक्त राज्य',
	),
	'UY' => array(
		'en' => 'Uruguay',
		'fr' => 'Uruguay',
		'es' => 'Uruguay',
		'it' => 'Uruguay',
		'hi' => 'उरुग्वे',
	),
	'UZ' => array(
		'en' => 'Uzbekistan',
		'fr' => 'Ouzbékistan',
		'es' => 'Uzbekistán',
		'it' => 'Uzbekistan',
		'hi' => 'उज़्बेकिस्तान',
	),
	'VA' => array(
		'en' => 'Vatican City',
		'fr' => 'État de la Cité du Vatican',
		'es' => 'Ciudad del Vaticano',
		'it' => 'Città del Vaticano',
		'hi' => 'वेटिकन शहर',
	),
	'VC' => array(
		'en' => 'Saint Vincent and the Grenadines',
		'fr' => 'Saint-Vincent-et-les Grenadines',
		'es' => 'San Vicente y las Granadinas',
		'it' => 'Saint Vincent e Grenadine',
		'hi' => 'सेंट विन्सेंट और ग्रेनेडाइंस',
	),
	'VE' => array(
		'en' => 'Venezuela',
		'fr' => 'Venezuela',
		'es' => 'Venezuela',
		'it' => 'Venezuela',
		'hi' => 'वेनज़ुएला',
	),
	'VG' => array(
		'en' => 'British Virgin Islands',
		'fr' => 'Îles Vierges britanniques',
		'es' => 'Islas Vírgenes Británicas',
		'it' => 'Isole Vergini Britanniche',
		'hi' => 'ब्रिटिश वर्जिन द्वीपसमूह',
	),
	'VI' => array(
		'en' => 'U.S. Virgin Islands',
		'fr' => 'Îles Vierges des États-Unis',
		'es' => 'Islas Vírgenes de EE. UU.',
		'it' => 'Isole Vergini Americane',
		'hi' => 'यू.एस. वर्जिन द्वीपसमूह',
	),
	'VN' => array(
		'en' => 'Vietnam',
		'fr' => 'Viêt Nam',
		'es' => 'Vietnam',
		'it' => 'Vietnam',
		'hi' => 'वियतनाम',
	),
	'VU' => array(
		'en' => 'Vanuatu',
		'fr' => 'Vanuatu',
		'es' => 'Vanuatu',
		'it' => 'Vanuatu',
		'hi' => 'वanuatu',
	),
	'WF' => array(
		'en' => 'Wallis and Futuna',
		'fr' => 'Wallis-et-Futuna',
		'es' => 'Wallis y Futuna',
		'it' => 'Wallis e Futuna',
		'hi' => 'वालिस और फ्यूचुना',
	),
	'WS' => array(
		'en' => 'Samoa',
		'fr' => 'Samoa',
		'es' => 'Samoa',
		'it' => 'Samoa',
		'hi' => 'सामोआ',
	),
	'YE' => array(
		'en' => 'Yemen',
		'fr' => 'Yémen',
		'es' => 'Yemen',
		'it' => 'Yemen',
		'hi' => 'यमन',
	),
	'YT' => array(
		'en' => 'Mayotte',
		'fr' => 'Mayotte',
		'es' => 'Mayotte',
		'it' => 'Mayotte',
		'hi' => 'मायोटे',
	),
	'ZA' => array(
		'en' => 'South Africa',
		'fr' => 'Afrique du Sud',
		'es' => 'Sudáfrica',
		'it' => 'Sudafrica',
		'hi' => 'दक्षिण अफ्रीका',
	),
	'ZM' => array(
		'en' => 'Zambia',
		'fr' => 'Zambie',
		'es' => 'Zambia',
		'it' => 'Zambia',
		'hi' => 'ज़ाम्बिया',
	),
	'ZW' => array(
		'en' => 'Zimbabwe',
		'fr' => 'Zimbabwe',
		'es' => 'Zimbabue',
		'it' => 'Zimbabwe',
		'hi' => 'ज़िम्बाब्वे',
	),
);

return apply_filters( 'eac_condition_language', $country_list );
