<?php

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * $features_list
 *
 * On peut ajouter/supprimer
 * NE JAMAIS CHANGER LE NOM DES CLÉS
 * Ne JAMAIS SUPPRIMER et AJOUTER UNE CLÉ DANS LA MÊME VERSION
 */
$features_list = array(
	'all-features-advanced' => array(
		'active'         => true,
		'title'          => esc_html__( 'Switch on all components', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => '',
		'help_url_class' => '',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-dynamic-tag'       => array(
		'active'         => true,
		'title'          => esc_html__( 'ACF dynamic tags', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/how-to-integrate-and-use-acf-fields-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Acf\\DynamicTags\\Eac_Acf_Tags',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-image-gallery'  => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF gallery field', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups', 'acf_register_field_type' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/add-and-publish-an-image-gallery-with-the-free-version-of-acf/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_INCLUDES_PATH . 'acf/fields/gallery/eac-acf-gallery-field.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-field-repeater' => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF repeater field', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups', 'acf_register_field_type' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/how-to-use-and-display-the-acf-repeater-field-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_INCLUDES_PATH . 'acf/fields/repeater/eac-acf-repeater-field.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-option-page'       => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF options page', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/add-options-page-for-the-free-version-of-acf/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-json'              => array(
		'active'         => false,
		'title'          => 'ACF JSON',
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => '#',
		'help_url_class' => 'eac-admin-help acf-json',
		'file_path'      => EAC_INCLUDES_PATH . 'acf/eac-acf-json.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'alt-attribute'         => array(
		'active'         => false,
		'title'          => esc_html__( 'ALT attribute', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-external-image-for-elementor/#improve-your-seo-with-the-dynamic-tag-external-image',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Image',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'editor-role'    => array(
		'active'         => false,
		'title'          => esc_html__( 'Content role manager', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/using-role-manager-module-elementor/#restrict-publication-modifications-to-content-only',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Role_Manager',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'custom-attribute'      => array(
		'active'         => false,
		'title'          => esc_html__( 'Custom attributes', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/add-your-custom-attributes-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\CustomAttributes\\Eac_Custom_Attributes',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'custom-css'            => array(
		'active'         => true,
		'title'          => esc_html__( 'Custom CSS', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/elementor-custom-css/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\CustomCss\\Eac_Custom_Css',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'dynamic-tag'           => array(
		'active'         => true,
		'title'          => esc_html__( 'Dynamic tags', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/elementor-dynamic-tags/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\DynamicTags\\Eac_Dynamic_Tags',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'dysplay-condition'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Display conditions', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/how-to-set-display-conditions-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'DisplayConditions\\Module',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'kenburns-slideshow'    => array(
		'active'         => false,
		'title'          => esc_html__( 'Ken Burns effect', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/animation-dimages/#ken-burns-slideshow-for-background-images',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Kenburns',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'element-link'          => array(
		'active'         => false,
		'title'          => esc_html__( 'Link element', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-link-to-a-section-column-using-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Links',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'lottie-background'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Lottie background', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/add-lottie-animation-in-elementor/#use-lottie-animations-in-the-background-of-an-element',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Lottie',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'motion-effects'        => array(
		'active'         => false,
		'title'          => esc_html__( 'Motion effects', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/create-animation-effects-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Effect',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'background-images'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Multiple background images', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-multiple-background-images-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Background_Images',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'element-sticky'        => array(
		'active'         => false,
		'title'          => esc_html__( 'Sticky element', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/use-sticky-scrolling-effect-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Elementor\\Injection\\Eac_Injection_Sticky',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'woo-dynamic-tag'       => array(
		'active'         => false,
		'title'          => esc_html__( 'WC dynamic tags', 'eac-components' ),
		'class_depends'  => array( 'WooCommerce' ),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/dynamic-woocommerce-tags-for-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_INCLUDES_NAMESPACE . 'Woocommerce\\DynamicTags\\Eac_Woo_Tags',
		'badge'          => '',
		'tab'            => 'feature',
	),
	'all-features-common'   => array(
		'active'         => false,
		'title'          => esc_html__( 'Switch on all components', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => '',
		'help_url_class' => '',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
	'acf-block-gallery' => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF gallery block', 'eac-components' ),
		'name'           => 'eac-blocks/gallery',
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/display-acf-gallery-field-using-a-gutenberg-block/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_INCLUDES_PATH . 'blocks/gallery/block.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-block-relationship' => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF relationship block', 'eac-components' ),
		'name'           => 'eac-blocks/relationship',
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/display-acf-relationship-field-using-a-gutenberg-block/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_INCLUDES_PATH . 'blocks/relationship/block.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'acf-block-repeater' => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF repeater block', 'eac-components' ),
		'name'           => 'eac-blocks/repeater',
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/display-acf-repeater-field-using-a-gutenberg-block/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_INCLUDES_PATH . 'blocks/repeater/block.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'acf',
	),
	'custom-nav-menu'       => array(
		'active'         => false,
		'title'          => esc_html__( 'Customize nav menu', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/customize-wordpress-navigation-menus/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => EAC_ADMIN_NAMESPACE . 'Eac_Load_Nav_Menu',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
	'grant-option-page'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Grant access Options Page', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/add-options-page-for-the-free-version-of-acf/#grant-access-options-page',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
	'extend-fields-medias'  => array(
		'active'         => false,
		'title'          => esc_html__( 'Media custom fields', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/create-advanced-image-gallery-using-elementor/#activate-a-link-and-add-keywords-to-the-filter',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
	'preload-page'  => array(
		'active'         => false,
		'title'          => esc_html__( 'Page preloading', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://instant.page/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
	'widget-count'  => array(
		'active'         => false,
		'title'          => esc_html__( 'Element usage', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => '#',
		'help_url_class' => 'eac-admin-help grant-elements-usage',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
	'block-meteo' => array(
		'active'         => false,
		'title'          => esc_html__( 'Weather block', 'eac-components' ),
		'name'           => 'eac-blocks/meteo',
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-a-weather-widget-using-a-gutenberg-block/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_INCLUDES_PATH . 'blocks/meteo/block.php',
		'name_space'     => '',
		'badge'          => '',
		'tab'            => 'wordpress',
	),
);

return $features_list;
